// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: token/v1/token.proto

package tokenv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/team-loco/loco/shared/proto/token/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TokenServiceName is the fully-qualified name of the TokenService service.
	TokenServiceName = "token.v1.TokenService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TokenServiceCreateTokenProcedure is the fully-qualified name of the TokenService's CreateToken
	// RPC.
	TokenServiceCreateTokenProcedure = "/token.v1.TokenService/CreateToken"
	// TokenServiceListTokensProcedure is the fully-qualified name of the TokenService's ListTokens RPC.
	TokenServiceListTokensProcedure = "/token.v1.TokenService/ListTokens"
	// TokenServiceGetTokenProcedure is the fully-qualified name of the TokenService's GetToken RPC.
	TokenServiceGetTokenProcedure = "/token.v1.TokenService/GetToken"
	// TokenServiceRevokeTokenProcedure is the fully-qualified name of the TokenService's RevokeToken
	// RPC.
	TokenServiceRevokeTokenProcedure = "/token.v1.TokenService/RevokeToken"
)

// TokenServiceClient is a client for the token.v1.TokenService service.
type TokenServiceClient interface {
	// CreateToken issues a new token for a specific entity with defined scopes.
	CreateToken(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error)
	// ListTokens lists all tokens associated with an entity.
	ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error)
	// GetToken retrieves metadata for a specific token (does not return the token string).
	GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error)
	// RevokeToken revokes/deletes a token.
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
}

// NewTokenServiceClient constructs a client for the token.v1.TokenService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTokenServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TokenServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tokenServiceMethods := v1.File_token_v1_token_proto.Services().ByName("TokenService").Methods()
	return &tokenServiceClient{
		createToken: connect.NewClient[v1.CreateTokenRequest, v1.CreateTokenResponse](
			httpClient,
			baseURL+TokenServiceCreateTokenProcedure,
			connect.WithSchema(tokenServiceMethods.ByName("CreateToken")),
			connect.WithClientOptions(opts...),
		),
		listTokens: connect.NewClient[v1.ListTokensRequest, v1.ListTokensResponse](
			httpClient,
			baseURL+TokenServiceListTokensProcedure,
			connect.WithSchema(tokenServiceMethods.ByName("ListTokens")),
			connect.WithClientOptions(opts...),
		),
		getToken: connect.NewClient[v1.GetTokenRequest, v1.GetTokenResponse](
			httpClient,
			baseURL+TokenServiceGetTokenProcedure,
			connect.WithSchema(tokenServiceMethods.ByName("GetToken")),
			connect.WithClientOptions(opts...),
		),
		revokeToken: connect.NewClient[v1.RevokeTokenRequest, v1.RevokeTokenResponse](
			httpClient,
			baseURL+TokenServiceRevokeTokenProcedure,
			connect.WithSchema(tokenServiceMethods.ByName("RevokeToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tokenServiceClient implements TokenServiceClient.
type tokenServiceClient struct {
	createToken *connect.Client[v1.CreateTokenRequest, v1.CreateTokenResponse]
	listTokens  *connect.Client[v1.ListTokensRequest, v1.ListTokensResponse]
	getToken    *connect.Client[v1.GetTokenRequest, v1.GetTokenResponse]
	revokeToken *connect.Client[v1.RevokeTokenRequest, v1.RevokeTokenResponse]
}

// CreateToken calls token.v1.TokenService.CreateToken.
func (c *tokenServiceClient) CreateToken(ctx context.Context, req *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	return c.createToken.CallUnary(ctx, req)
}

// ListTokens calls token.v1.TokenService.ListTokens.
func (c *tokenServiceClient) ListTokens(ctx context.Context, req *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	return c.listTokens.CallUnary(ctx, req)
}

// GetToken calls token.v1.TokenService.GetToken.
func (c *tokenServiceClient) GetToken(ctx context.Context, req *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error) {
	return c.getToken.CallUnary(ctx, req)
}

// RevokeToken calls token.v1.TokenService.RevokeToken.
func (c *tokenServiceClient) RevokeToken(ctx context.Context, req *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return c.revokeToken.CallUnary(ctx, req)
}

// TokenServiceHandler is an implementation of the token.v1.TokenService service.
type TokenServiceHandler interface {
	// CreateToken issues a new token for a specific entity with defined scopes.
	CreateToken(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error)
	// ListTokens lists all tokens associated with an entity.
	ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error)
	// GetToken retrieves metadata for a specific token (does not return the token string).
	GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error)
	// RevokeToken revokes/deletes a token.
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
}

// NewTokenServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTokenServiceHandler(svc TokenServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tokenServiceMethods := v1.File_token_v1_token_proto.Services().ByName("TokenService").Methods()
	tokenServiceCreateTokenHandler := connect.NewUnaryHandler(
		TokenServiceCreateTokenProcedure,
		svc.CreateToken,
		connect.WithSchema(tokenServiceMethods.ByName("CreateToken")),
		connect.WithHandlerOptions(opts...),
	)
	tokenServiceListTokensHandler := connect.NewUnaryHandler(
		TokenServiceListTokensProcedure,
		svc.ListTokens,
		connect.WithSchema(tokenServiceMethods.ByName("ListTokens")),
		connect.WithHandlerOptions(opts...),
	)
	tokenServiceGetTokenHandler := connect.NewUnaryHandler(
		TokenServiceGetTokenProcedure,
		svc.GetToken,
		connect.WithSchema(tokenServiceMethods.ByName("GetToken")),
		connect.WithHandlerOptions(opts...),
	)
	tokenServiceRevokeTokenHandler := connect.NewUnaryHandler(
		TokenServiceRevokeTokenProcedure,
		svc.RevokeToken,
		connect.WithSchema(tokenServiceMethods.ByName("RevokeToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/token.v1.TokenService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TokenServiceCreateTokenProcedure:
			tokenServiceCreateTokenHandler.ServeHTTP(w, r)
		case TokenServiceListTokensProcedure:
			tokenServiceListTokensHandler.ServeHTTP(w, r)
		case TokenServiceGetTokenProcedure:
			tokenServiceGetTokenHandler.ServeHTTP(w, r)
		case TokenServiceRevokeTokenProcedure:
			tokenServiceRevokeTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTokenServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTokenServiceHandler struct{}

func (UnimplementedTokenServiceHandler) CreateToken(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("token.v1.TokenService.CreateToken is not implemented"))
}

func (UnimplementedTokenServiceHandler) ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("token.v1.TokenService.ListTokens is not implemented"))
}

func (UnimplementedTokenServiceHandler) GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("token.v1.TokenService.GetToken is not implemented"))
}

func (UnimplementedTokenServiceHandler) RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("token.v1.TokenService.RevokeToken is not implemented"))
}
