default_install_hook_types: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: lint-go
        name: make lint-go
        language: system
        entry: scripts/golangci-lint-modules.sh
        files: (\.go|(^|/)go\.(mod|sum))$
        exclude: ^gen/
        require_serial: true

      - id: lint-proto
        name: make lint-proto
        language: system
        entry: make lint-proto
        files: (\.proto|(^|/)buf\.(yaml|lock))$
        pass_filenames: false

      - id: lint-web
        name: make lint-web
        language: system
        entry: make lint-web
        files: ^(web/|gen/ts/)
        pass_filenames: false

      - id: lint-actions
        name: make lint-actions
        language: system
        entry: make lint-actions
        files: ^\.github/workflows/
        pass_filenames: false
