---
environments:
  local:
    values:
      - environment: local

  prod:
    values:
      - environment: prod
      - locoCore:
          secrets:
            cloudflareToken: {{ requiredEnv "CLOUDFLARE_TOKEN" }}
            env:
              GITLAB_PAT: {{ requiredEnv "GITLAB_PAT" }}
              GITLAB_PROJECT_ID: {{ requiredEnv "GITLAB_PROJECT_ID" }}
              GITLAB_TOKEN_NAME: {{ requiredEnv "GITLAB_TOKEN_NAME" }}
              GITLAB_URL: {{ requiredEnv "GITLAB_URL" }}
              GITLAB_REGISTRY_URL: {{ requiredEnv "GITLAB_REGISTRY_URL" }}
              GITLAB_DEPLOY_TOKEN_NAME: {{ requiredEnv "GITLAB_DEPLOY_TOKEN_NAME" }}

              GH_OAUTH_CLIENT_ID: {{ requiredEnv "GH_OAUTH_CLIENT_ID" }}
              GH_OAUTH_CLIENT_SECRET: {{ requiredEnv "GH_OAUTH_CLIENT_SECRET" }}
              GH_OAUTH_REDIRECT_URL: {{ requiredEnv "GH_OAUTH_REDIRECT_URL" }}
              GH_OAUTH_STATE: {{ requiredEnv "GH_OAUTH_STATE" }}

              APP_ENV: {{ requiredEnv "APP_ENV" }}
              LOG_LEVEL: {{ requiredEnv "LOG_LEVEL" }}
              PORT: {{ requiredEnv "PORT" }}
              DATABASE_URL: {{ requiredEnv "DATABASE_URL" }}
              JWT_SECRET: {{ requiredEnv "JWT_SECRET" }}

              REGISTRY_TAG: {{ requiredEnv "REGISTRY_TAG" }}

---
helmDefaults:
  wait: false
  timeout: 600
  cleanupOnFail: true

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: cilium
    url: https://helm.cilium.io
  - name: altinity
    url: https://helm.altinity.com
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
  # phase 1: networking
  - name: loco-networking
    chart: ./charts/loco-networking
    namespace: kube-system
    createNamespace: true
    labels:
      phase: "1-networking"
    values:
      - ./charts/loco-networking/values.yaml

  # phase 2: core
  - name: cert-manager
    chart: jetstack/cert-manager
    version: v1.19.1
    namespace: cert-manager
    createNamespace: true
    needs:
      - kube-system/loco-networking
    labels:
      phase: "2-core"
    set:
      - name: crds.enabled
        value: true

  - name: loco-core
    chart: ./charts/loco-core
    namespace: loco-system
    createNamespace: true
    needs:
      - cert-manager/cert-manager
    labels:
      phase: "2-core"
      component: "app"
    values:
      - ./charts/loco-core/values.yaml
      - {{ .Environment.Values.locoCore | default dict }}

  # phase 3: observability
  - name: loco-obs
    chart: ./charts/loco-obs
    namespace: observability
    createNamespace: true
    needs:
      - loco-system/loco-core
    labels:
      phase: "3-observability"
    values:
      - ./charts/loco-obs/values.yaml
