kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: loco-cluster-local
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  apiServerAddress: 127.0.0.1
  disableDefaultCNI: true
  kubeProxyMode: "none"
