min_version = "2026.9.15"

[tools]
go = "1.27.0"
bun = "1.4.0"

buf = "1.73.0"
"github:sqlc-dev/sqlc" = "1.31.1"
yq = "4.49.2"
"github:kubernetes-sigs/controller-tools" = { version = "0.19.0", bin = "controller-gen" }
kustomize = "5.7.1"

golangci-lint = "2.13.2"
actionlint = "1.7.12"
hadolint = "2.15.1"

helm = "4.3.0"
helmfile = "1.8.1"
kubectl = "1.32.13"
kind = "0.33.0"
tilt = "0.37.7"
air = "1.61.5"

terraform = "1.16.4"
doctl = "1.175.0"

[settings]
lockfile = true
locked = true

[env]
GOTOOLCHAIN = "local"
