// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: loco/workspace/v1/workspace.proto

package workspacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workspace represents a project container within an organization where resources are deployed and managed.
type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         int64                  `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workspace) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workspace) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Workspace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workspace) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// WorkspaceMember represents a user's membership and role assignment in a workspace.
type WorkspaceMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceMember) Reset() {
	*x = WorkspaceMember{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMember) ProtoMessage() {}

func (x *WorkspaceMember) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMember.ProtoReflect.Descriptor instead.
func (*WorkspaceMember) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceMember) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *WorkspaceMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WorkspaceMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkspaceMember) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// WorkspaceMemberWithUser includes user details along with membership information for convenient retrieval.
type WorkspaceMemberWithUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserEmail     string                 `protobuf:"bytes,6,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserAvatarUrl string                 `protobuf:"bytes,7,opt,name=user_avatar_url,json=userAvatarUrl,proto3" json:"user_avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceMemberWithUser) Reset() {
	*x = WorkspaceMemberWithUser{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMemberWithUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMemberWithUser) ProtoMessage() {}

func (x *WorkspaceMemberWithUser) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMemberWithUser.ProtoReflect.Descriptor instead.
func (*WorkspaceMemberWithUser) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *WorkspaceMemberWithUser) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *WorkspaceMemberWithUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WorkspaceMemberWithUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkspaceMemberWithUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkspaceMemberWithUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *WorkspaceMemberWithUser) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *WorkspaceMemberWithUser) GetUserAvatarUrl() string {
	if x != nil {
		return x.UserAvatarUrl
	}
	return ""
}

// CreateWorkspaceRequest is the request to create a new workspace.
type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWorkspaceRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CreateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// CreateWorkspaceResponse is the response containing the created workspace ID.
type CreateWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceResponse) Reset() {
	*x = CreateWorkspaceResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceResponse) ProtoMessage() {}

func (x *CreateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkspaceResponse) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

// GetWorkspaceRequest is the request to retrieve a workspace.
type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkspaceRequest) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

// GetWorkspaceResponse is the response containing the workspace.
type GetWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceResponse) Reset() {
	*x = GetWorkspaceResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceResponse) ProtoMessage() {}

func (x *GetWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

// ListUserWorkspacesRequest is the request to list workspaces for a user.
type ListUserWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // default: 50, max: 200
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // cursor from previous page (base64-encoded timestamp+id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserWorkspacesRequest) Reset() {
	*x = ListUserWorkspacesRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserWorkspacesRequest) ProtoMessage() {}

func (x *ListUserWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListUserWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserWorkspacesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserWorkspacesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserWorkspacesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListUserWorkspacesResponse contains the list of user's workspaces.
type ListUserWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // empty if no more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserWorkspacesResponse) Reset() {
	*x = ListUserWorkspacesResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserWorkspacesResponse) ProtoMessage() {}

func (x *ListUserWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListUserWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *ListUserWorkspacesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// ListOrgWorkspacesRequest is the request to list workspaces in an organization.
type ListOrgWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // default: 50, max: 200
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // cursor from previous page (base64-encoded timestamp+id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrgWorkspacesRequest) Reset() {
	*x = ListOrgWorkspacesRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrgWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgWorkspacesRequest) ProtoMessage() {}

func (x *ListOrgWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListOrgWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrgWorkspacesRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *ListOrgWorkspacesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrgWorkspacesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListOrgWorkspacesResponse contains the list of workspaces.
type ListOrgWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // empty if no more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrgWorkspacesResponse) Reset() {
	*x = ListOrgWorkspacesResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrgWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgWorkspacesResponse) ProtoMessage() {}

func (x *ListOrgWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListOrgWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrgWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *ListOrgWorkspacesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateWorkspaceRequest is the request to update a workspace.
type UpdateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateWorkspaceRequest) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *UpdateWorkspaceRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateWorkspaceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// UpdateWorkspaceResponse is the response containing the updated workspace ID.
type UpdateWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceResponse) Reset() {
	*x = UpdateWorkspaceResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceResponse) ProtoMessage() {}

func (x *UpdateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateWorkspaceResponse) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

// DeleteWorkspaceRequest is the request to delete a workspace.
type DeleteWorkspaceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId       int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ConfirmDeleteApps bool                   `protobuf:"varint,2,opt,name=confirm_delete_apps,json=confirmDeleteApps,proto3" json:"confirm_delete_apps,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteWorkspaceRequest) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *DeleteWorkspaceRequest) GetConfirmDeleteApps() bool {
	if x != nil {
		return x.ConfirmDeleteApps
	}
	return false
}

// DeleteWorkspaceResponse is the response after deleting a workspace.
type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{14}
}

// CreateMemberRequest is the request to add a member to a workspace.
type CreateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberRequest) Reset() {
	*x = CreateMemberRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberRequest) ProtoMessage() {}

func (x *CreateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberRequest.ProtoReflect.Descriptor instead.
func (*CreateMemberRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{15}
}

func (x *CreateMemberRequest) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *CreateMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// CreateMemberResponse is the response containing the workspace and user IDs.
type CreateMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberResponse) Reset() {
	*x = CreateMemberResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberResponse) ProtoMessage() {}

func (x *CreateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberResponse.ProtoReflect.Descriptor instead.
func (*CreateMemberResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{16}
}

func (x *CreateMemberResponse) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *CreateMemberResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// DeleteMemberRequest is the request to remove a member from a workspace.
type DeleteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberRequest) Reset() {
	*x = DeleteMemberRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberRequest) ProtoMessage() {}

func (x *DeleteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteMemberRequest) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *DeleteMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// DeleteMemberResponse is the response after removing a member from a workspace.
type DeleteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberResponse) Reset() {
	*x = DeleteMemberResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberResponse) ProtoMessage() {}

func (x *DeleteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemberResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{18}
}

// ListWorkspaceMembersRequest is the request to list members of a workspace.
type ListWorkspaceMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // default: 50, max: 200
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // cursor from previous page (base64-encoded timestamp+id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersRequest) Reset() {
	*x = ListWorkspaceMembersRequest{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersRequest) ProtoMessage() {}

func (x *ListWorkspaceMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersRequest) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{19}
}

func (x *ListWorkspaceMembersRequest) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *ListWorkspaceMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkspaceMembersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListWorkspaceMembersResponse contains the list of workspace members.
type ListWorkspaceMembersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Members       []*WorkspaceMemberWithUser `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	NextPageToken string                     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // empty if no more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersResponse) Reset() {
	*x = ListWorkspaceMembersResponse{}
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersResponse) ProtoMessage() {}

func (x *ListWorkspaceMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_workspace_v1_workspace_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersResponse) Descriptor() ([]byte, []int) {
	return file_loco_workspace_v1_workspace_proto_rawDescGZIP(), []int{20}
}

func (x *ListWorkspaceMembersResponse) GetMembers() []*WorkspaceMemberWithUser {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListWorkspaceMembersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_loco_workspace_v1_workspace_proto protoreflect.FileDescriptor

const file_loco_workspace_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"!loco/workspace/v1/workspace.proto\x12\x11loco.workspace.v1\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\x03R\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\x03R\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x01\n" +
	"\x0fWorkspaceMember\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x88\x02\n" +
	"\x17WorkspaceMemberWithUser\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"user_email\x18\x06 \x01(\tR\tuserEmail\x12&\n" +
	"\x0fuser_avatar_url\x18\a \x01(\tR\ruserAvatarUrl\"z\n" +
	"\x16CreateWorkspaceRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"<\n" +
	"\x17CreateWorkspaceResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\"8\n" +
	"\x13GetWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\"R\n" +
	"\x14GetWorkspaceResponse\x12:\n" +
	"\tworkspace\x18\x01 \x01(\v2\x1c.loco.workspace.v1.WorkspaceR\tworkspace\"p\n" +
	"\x19ListUserWorkspacesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x82\x01\n" +
	"\x1aListUserWorkspacesResponse\x12<\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x1c.loco.workspace.v1.WorkspaceR\n" +
	"workspaces\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"m\n" +
	"\x18ListOrgWorkspacesRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x81\x01\n" +
	"\x19ListOrgWorkspacesResponse\x12<\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x1c.loco.workspace.v1.WorkspaceR\n" +
	"workspaces\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd1\x01\n" +
	"\x16UpdateWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"<\n" +
	"\x17UpdateWorkspaceResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\"k\n" +
	"\x16DeleteWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12.\n" +
	"\x13confirm_delete_apps\x18\x02 \x01(\bR\x11confirmDeleteApps\"\x19\n" +
	"\x17DeleteWorkspaceResponse\"e\n" +
	"\x13CreateMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"R\n" +
	"\x14CreateMemberResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"Q\n" +
	"\x13DeleteMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x16\n" +
	"\x14DeleteMemberResponse\"|\n" +
	"\x1bListWorkspaceMembersRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8c\x01\n" +
	"\x1cListWorkspaceMembersResponse\x12D\n" +
	"\amembers\x18\x01 \x03(\v2*.loco.workspace.v1.WorkspaceMemberWithUserR\amembers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xcf\a\n" +
	"\x10WorkspaceService\x12h\n" +
	"\x0fCreateWorkspace\x12).loco.workspace.v1.CreateWorkspaceRequest\x1a*.loco.workspace.v1.CreateWorkspaceResponse\x12_\n" +
	"\fGetWorkspace\x12&.loco.workspace.v1.GetWorkspaceRequest\x1a'.loco.workspace.v1.GetWorkspaceResponse\x12h\n" +
	"\x0fUpdateWorkspace\x12).loco.workspace.v1.UpdateWorkspaceRequest\x1a*.loco.workspace.v1.UpdateWorkspaceResponse\x12h\n" +
	"\x0fDeleteWorkspace\x12).loco.workspace.v1.DeleteWorkspaceRequest\x1a*.loco.workspace.v1.DeleteWorkspaceResponse\x12q\n" +
	"\x12ListUserWorkspaces\x12,.loco.workspace.v1.ListUserWorkspacesRequest\x1a-.loco.workspace.v1.ListUserWorkspacesResponse\x12n\n" +
	"\x11ListOrgWorkspaces\x12+.loco.workspace.v1.ListOrgWorkspacesRequest\x1a,.loco.workspace.v1.ListOrgWorkspacesResponse\x12_\n" +
	"\fCreateMember\x12&.loco.workspace.v1.CreateMemberRequest\x1a'.loco.workspace.v1.CreateMemberResponse\x12_\n" +
	"\fDeleteMember\x12&.loco.workspace.v1.DeleteMemberRequest\x1a'.loco.workspace.v1.DeleteMemberResponse\x12w\n" +
	"\x14ListWorkspaceMembers\x12..loco.workspace.v1.ListWorkspaceMembersRequest\x1a/.loco.workspace.v1.ListWorkspaceMembersResponseBFZDgithub.com/team-loco/loco/shared/proto/loco/workspace/v1;workspacev1b\x06proto3"

var (
	file_loco_workspace_v1_workspace_proto_rawDescOnce sync.Once
	file_loco_workspace_v1_workspace_proto_rawDescData []byte
)

func file_loco_workspace_v1_workspace_proto_rawDescGZIP() []byte {
	file_loco_workspace_v1_workspace_proto_rawDescOnce.Do(func() {
		file_loco_workspace_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loco_workspace_v1_workspace_proto_rawDesc), len(file_loco_workspace_v1_workspace_proto_rawDesc)))
	})
	return file_loco_workspace_v1_workspace_proto_rawDescData
}

var file_loco_workspace_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_loco_workspace_v1_workspace_proto_goTypes = []any{
	(*Workspace)(nil),                    // 0: loco.workspace.v1.Workspace
	(*WorkspaceMember)(nil),              // 1: loco.workspace.v1.WorkspaceMember
	(*WorkspaceMemberWithUser)(nil),      // 2: loco.workspace.v1.WorkspaceMemberWithUser
	(*CreateWorkspaceRequest)(nil),       // 3: loco.workspace.v1.CreateWorkspaceRequest
	(*CreateWorkspaceResponse)(nil),      // 4: loco.workspace.v1.CreateWorkspaceResponse
	(*GetWorkspaceRequest)(nil),          // 5: loco.workspace.v1.GetWorkspaceRequest
	(*GetWorkspaceResponse)(nil),         // 6: loco.workspace.v1.GetWorkspaceResponse
	(*ListUserWorkspacesRequest)(nil),    // 7: loco.workspace.v1.ListUserWorkspacesRequest
	(*ListUserWorkspacesResponse)(nil),   // 8: loco.workspace.v1.ListUserWorkspacesResponse
	(*ListOrgWorkspacesRequest)(nil),     // 9: loco.workspace.v1.ListOrgWorkspacesRequest
	(*ListOrgWorkspacesResponse)(nil),    // 10: loco.workspace.v1.ListOrgWorkspacesResponse
	(*UpdateWorkspaceRequest)(nil),       // 11: loco.workspace.v1.UpdateWorkspaceRequest
	(*UpdateWorkspaceResponse)(nil),      // 12: loco.workspace.v1.UpdateWorkspaceResponse
	(*DeleteWorkspaceRequest)(nil),       // 13: loco.workspace.v1.DeleteWorkspaceRequest
	(*DeleteWorkspaceResponse)(nil),      // 14: loco.workspace.v1.DeleteWorkspaceResponse
	(*CreateMemberRequest)(nil),          // 15: loco.workspace.v1.CreateMemberRequest
	(*CreateMemberResponse)(nil),         // 16: loco.workspace.v1.CreateMemberResponse
	(*DeleteMemberRequest)(nil),          // 17: loco.workspace.v1.DeleteMemberRequest
	(*DeleteMemberResponse)(nil),         // 18: loco.workspace.v1.DeleteMemberResponse
	(*ListWorkspaceMembersRequest)(nil),  // 19: loco.workspace.v1.ListWorkspaceMembersRequest
	(*ListWorkspaceMembersResponse)(nil), // 20: loco.workspace.v1.ListWorkspaceMembersResponse
	(*timestamppb.Timestamp)(nil),        // 21: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),        // 22: google.protobuf.FieldMask
}
var file_loco_workspace_v1_workspace_proto_depIdxs = []int32{
	21, // 0: loco.workspace.v1.Workspace.created_at:type_name -> google.protobuf.Timestamp
	21, // 1: loco.workspace.v1.Workspace.updated_at:type_name -> google.protobuf.Timestamp
	21, // 2: loco.workspace.v1.WorkspaceMember.created_at:type_name -> google.protobuf.Timestamp
	21, // 3: loco.workspace.v1.WorkspaceMemberWithUser.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: loco.workspace.v1.GetWorkspaceResponse.workspace:type_name -> loco.workspace.v1.Workspace
	0,  // 5: loco.workspace.v1.ListUserWorkspacesResponse.workspaces:type_name -> loco.workspace.v1.Workspace
	0,  // 6: loco.workspace.v1.ListOrgWorkspacesResponse.workspaces:type_name -> loco.workspace.v1.Workspace
	22, // 7: loco.workspace.v1.UpdateWorkspaceRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 8: loco.workspace.v1.ListWorkspaceMembersResponse.members:type_name -> loco.workspace.v1.WorkspaceMemberWithUser
	3,  // 9: loco.workspace.v1.WorkspaceService.CreateWorkspace:input_type -> loco.workspace.v1.CreateWorkspaceRequest
	5,  // 10: loco.workspace.v1.WorkspaceService.GetWorkspace:input_type -> loco.workspace.v1.GetWorkspaceRequest
	11, // 11: loco.workspace.v1.WorkspaceService.UpdateWorkspace:input_type -> loco.workspace.v1.UpdateWorkspaceRequest
	13, // 12: loco.workspace.v1.WorkspaceService.DeleteWorkspace:input_type -> loco.workspace.v1.DeleteWorkspaceRequest
	7,  // 13: loco.workspace.v1.WorkspaceService.ListUserWorkspaces:input_type -> loco.workspace.v1.ListUserWorkspacesRequest
	9,  // 14: loco.workspace.v1.WorkspaceService.ListOrgWorkspaces:input_type -> loco.workspace.v1.ListOrgWorkspacesRequest
	15, // 15: loco.workspace.v1.WorkspaceService.CreateMember:input_type -> loco.workspace.v1.CreateMemberRequest
	17, // 16: loco.workspace.v1.WorkspaceService.DeleteMember:input_type -> loco.workspace.v1.DeleteMemberRequest
	19, // 17: loco.workspace.v1.WorkspaceService.ListWorkspaceMembers:input_type -> loco.workspace.v1.ListWorkspaceMembersRequest
	4,  // 18: loco.workspace.v1.WorkspaceService.CreateWorkspace:output_type -> loco.workspace.v1.CreateWorkspaceResponse
	6,  // 19: loco.workspace.v1.WorkspaceService.GetWorkspace:output_type -> loco.workspace.v1.GetWorkspaceResponse
	12, // 20: loco.workspace.v1.WorkspaceService.UpdateWorkspace:output_type -> loco.workspace.v1.UpdateWorkspaceResponse
	14, // 21: loco.workspace.v1.WorkspaceService.DeleteWorkspace:output_type -> loco.workspace.v1.DeleteWorkspaceResponse
	8,  // 22: loco.workspace.v1.WorkspaceService.ListUserWorkspaces:output_type -> loco.workspace.v1.ListUserWorkspacesResponse
	10, // 23: loco.workspace.v1.WorkspaceService.ListOrgWorkspaces:output_type -> loco.workspace.v1.ListOrgWorkspacesResponse
	16, // 24: loco.workspace.v1.WorkspaceService.CreateMember:output_type -> loco.workspace.v1.CreateMemberResponse
	18, // 25: loco.workspace.v1.WorkspaceService.DeleteMember:output_type -> loco.workspace.v1.DeleteMemberResponse
	20, // 26: loco.workspace.v1.WorkspaceService.ListWorkspaceMembers:output_type -> loco.workspace.v1.ListWorkspaceMembersResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_loco_workspace_v1_workspace_proto_init() }
func file_loco_workspace_v1_workspace_proto_init() {
	if File_loco_workspace_v1_workspace_proto != nil {
		return
	}
	file_loco_workspace_v1_workspace_proto_msgTypes[3].OneofWrappers = []any{}
	file_loco_workspace_v1_workspace_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loco_workspace_v1_workspace_proto_rawDesc), len(file_loco_workspace_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loco_workspace_v1_workspace_proto_goTypes,
		DependencyIndexes: file_loco_workspace_v1_workspace_proto_depIdxs,
		MessageInfos:      file_loco_workspace_v1_workspace_proto_msgTypes,
	}.Build()
	File_loco_workspace_v1_workspace_proto = out.File
	file_loco_workspace_v1_workspace_proto_goTypes = nil
	file_loco_workspace_v1_workspace_proto_depIdxs = nil
}
