// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: loco/agent/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/team-loco/loco/proto/loco/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "loco.agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceRegisterProcedure is the fully-qualified name of the AgentService's Register RPC.
	AgentServiceRegisterProcedure = "/loco.agent.v1.AgentService/Register"
	// AgentServiceCommandStreamProcedure is the fully-qualified name of the AgentService's
	// CommandStream RPC.
	AgentServiceCommandStreamProcedure = "/loco.agent.v1.AgentService/CommandStream"
	// AgentServiceHeartbeatProcedure is the fully-qualified name of the AgentService's Heartbeat RPC.
	AgentServiceHeartbeatProcedure = "/loco.agent.v1.AgentService/Heartbeat"
	// AgentServiceReportStatusProcedure is the fully-qualified name of the AgentService's ReportStatus
	// RPC.
	AgentServiceReportStatusProcedure = "/loco.agent.v1.AgentService/ReportStatus"
)

// AgentServiceClient is a client for the loco.agent.v1.AgentService service.
type AgentServiceClient interface {
	// Register announces an agent to the control plane and returns the cluster ID.
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	// CommandStream is a bidirectional stream for command dispatch.
	// Control plane sends commands, agent sends acks back.
	CommandStream(context.Context) *connect.BidiStreamForClient[v1.CommandStreamRequest, v1.CommandStreamResponse]
	// Heartbeat is a bidirectional stream for agent health reporting.
	// Agent sends periodic heartbeats, control plane can send directives back.
	Heartbeat(context.Context) *connect.BidiStreamForClient[v1.HeartbeatRequest, v1.HeartbeatResponse]
	// ReportStatus reports deployment status changes from the agent.
	ReportStatus(context.Context, *connect.Request[v1.ReportStatusRequest]) (*connect.Response[v1.ReportStatusResponse], error)
}

// NewAgentServiceClient constructs a client for the loco.agent.v1.AgentService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_loco_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+AgentServiceRegisterProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		commandStream: connect.NewClient[v1.CommandStreamRequest, v1.CommandStreamResponse](
			httpClient,
			baseURL+AgentServiceCommandStreamProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CommandStream")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v1.HeartbeatRequest, v1.HeartbeatResponse](
			httpClient,
			baseURL+AgentServiceHeartbeatProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		reportStatus: connect.NewClient[v1.ReportStatusRequest, v1.ReportStatusResponse](
			httpClient,
			baseURL+AgentServiceReportStatusProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ReportStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	register      *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	commandStream *connect.Client[v1.CommandStreamRequest, v1.CommandStreamResponse]
	heartbeat     *connect.Client[v1.HeartbeatRequest, v1.HeartbeatResponse]
	reportStatus  *connect.Client[v1.ReportStatusRequest, v1.ReportStatusResponse]
}

// Register calls loco.agent.v1.AgentService.Register.
func (c *agentServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// CommandStream calls loco.agent.v1.AgentService.CommandStream.
func (c *agentServiceClient) CommandStream(ctx context.Context) *connect.BidiStreamForClient[v1.CommandStreamRequest, v1.CommandStreamResponse] {
	return c.commandStream.CallBidiStream(ctx)
}

// Heartbeat calls loco.agent.v1.AgentService.Heartbeat.
func (c *agentServiceClient) Heartbeat(ctx context.Context) *connect.BidiStreamForClient[v1.HeartbeatRequest, v1.HeartbeatResponse] {
	return c.heartbeat.CallBidiStream(ctx)
}

// ReportStatus calls loco.agent.v1.AgentService.ReportStatus.
func (c *agentServiceClient) ReportStatus(ctx context.Context, req *connect.Request[v1.ReportStatusRequest]) (*connect.Response[v1.ReportStatusResponse], error) {
	return c.reportStatus.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the loco.agent.v1.AgentService service.
type AgentServiceHandler interface {
	// Register announces an agent to the control plane and returns the cluster ID.
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	// CommandStream is a bidirectional stream for command dispatch.
	// Control plane sends commands, agent sends acks back.
	CommandStream(context.Context, *connect.BidiStream[v1.CommandStreamRequest, v1.CommandStreamResponse]) error
	// Heartbeat is a bidirectional stream for agent health reporting.
	// Agent sends periodic heartbeats, control plane can send directives back.
	Heartbeat(context.Context, *connect.BidiStream[v1.HeartbeatRequest, v1.HeartbeatResponse]) error
	// ReportStatus reports deployment status changes from the agent.
	ReportStatus(context.Context, *connect.Request[v1.ReportStatusRequest]) (*connect.Response[v1.ReportStatusResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_loco_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceRegisterHandler := connect.NewUnaryHandler(
		AgentServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(agentServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceCommandStreamHandler := connect.NewBidiStreamHandler(
		AgentServiceCommandStreamProcedure,
		svc.CommandStream,
		connect.WithSchema(agentServiceMethods.ByName("CommandStream")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceHeartbeatHandler := connect.NewBidiStreamHandler(
		AgentServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(agentServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceReportStatusHandler := connect.NewUnaryHandler(
		AgentServiceReportStatusProcedure,
		svc.ReportStatus,
		connect.WithSchema(agentServiceMethods.ByName("ReportStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/loco.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceRegisterProcedure:
			agentServiceRegisterHandler.ServeHTTP(w, r)
		case AgentServiceCommandStreamProcedure:
			agentServiceCommandStreamHandler.ServeHTTP(w, r)
		case AgentServiceHeartbeatProcedure:
			agentServiceHeartbeatHandler.ServeHTTP(w, r)
		case AgentServiceReportStatusProcedure:
			agentServiceReportStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.agent.v1.AgentService.Register is not implemented"))
}

func (UnimplementedAgentServiceHandler) CommandStream(context.Context, *connect.BidiStream[v1.CommandStreamRequest, v1.CommandStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("loco.agent.v1.AgentService.CommandStream is not implemented"))
}

func (UnimplementedAgentServiceHandler) Heartbeat(context.Context, *connect.BidiStream[v1.HeartbeatRequest, v1.HeartbeatResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("loco.agent.v1.AgentService.Heartbeat is not implemented"))
}

func (UnimplementedAgentServiceHandler) ReportStatus(context.Context, *connect.Request[v1.ReportStatusRequest]) (*connect.Response[v1.ReportStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.agent.v1.AgentService.ReportStatus is not implemented"))
}
