// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: oauth/v1/oauth.proto

package oauthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GithubOAuthDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubOAuthDetailsRequest) Reset() {
	*x = GithubOAuthDetailsRequest{}
	mi := &file_oauth_v1_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubOAuthDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubOAuthDetailsRequest) ProtoMessage() {}

func (x *GithubOAuthDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_v1_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubOAuthDetailsRequest.ProtoReflect.Descriptor instead.
func (*GithubOAuthDetailsRequest) Descriptor() ([]byte, []int) {
	return file_oauth_v1_oauth_proto_rawDescGZIP(), []int{0}
}

type GithubOAuthDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TokenTtl      float64                `protobuf:"fixed64,2,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubOAuthDetailsResponse) Reset() {
	*x = GithubOAuthDetailsResponse{}
	mi := &file_oauth_v1_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubOAuthDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubOAuthDetailsResponse) ProtoMessage() {}

func (x *GithubOAuthDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_v1_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubOAuthDetailsResponse.ProtoReflect.Descriptor instead.
func (*GithubOAuthDetailsResponse) Descriptor() ([]byte, []int) {
	return file_oauth_v1_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *GithubOAuthDetailsResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GithubOAuthDetailsResponse) GetTokenTtl() float64 {
	if x != nil {
		return x.TokenTtl
	}
	return 0
}

type ExchangeGithubTokenRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	GithubAccessToken     string                 `protobuf:"bytes,1,opt,name=github_access_token,json=githubAccessToken,proto3" json:"github_access_token,omitempty"`
	CreateUserIfNotExists bool                   `protobuf:"varint,2,opt,name=create_user_if_not_exists,json=createUserIfNotExists,proto3" json:"create_user_if_not_exists,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExchangeGithubTokenRequest) Reset() {
	*x = ExchangeGithubTokenRequest{}
	mi := &file_oauth_v1_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeGithubTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeGithubTokenRequest) ProtoMessage() {}

func (x *ExchangeGithubTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_v1_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeGithubTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeGithubTokenRequest) Descriptor() ([]byte, []int) {
	return file_oauth_v1_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeGithubTokenRequest) GetGithubAccessToken() string {
	if x != nil {
		return x.GithubAccessToken
	}
	return ""
}

func (x *ExchangeGithubTokenRequest) GetCreateUserIfNotExists() bool {
	if x != nil {
		return x.CreateUserIfNotExists
	}
	return false
}

type ExchangeGithubTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocoToken     string                 `protobuf:"bytes,1,opt,name=loco_token,json=locoToken,proto3" json:"loco_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeGithubTokenResponse) Reset() {
	*x = ExchangeGithubTokenResponse{}
	mi := &file_oauth_v1_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeGithubTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeGithubTokenResponse) ProtoMessage() {}

func (x *ExchangeGithubTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_v1_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeGithubTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeGithubTokenResponse) Descriptor() ([]byte, []int) {
	return file_oauth_v1_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeGithubTokenResponse) GetLocoToken() string {
	if x != nil {
		return x.LocoToken
	}
	return ""
}

func (x *ExchangeGithubTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *ExchangeGithubTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExchangeGithubTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetGithubAuthorizationURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGithubAuthorizationURLRequest) Reset() {
	*x = GetGithubAuthorizationURLRequest{}
	mi := &file_oauth_v1_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGithubAuthorizationURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubAuthorizationURLRequest) ProtoMessage() {}

func (x *GetGithubAuthorizationURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_v1_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubAuthorizationURLRequest.ProtoReflect.Descriptor instead.
func (*GetGithubAuthorizationURLRequest) Descriptor() ([]byte, []int) {
	return file_oauth_v1_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *GetGithubAuthorizationURLRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetGithubAuthorizationURLRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type GetGithubAuthorizationURLResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGithubAuthorizationURLResponse) Reset() {
	*x = GetGithubAuthorizationURLResponse{}
	mi := &file_oauth_v1_oauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGithubAuthorizationURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGithubAuthorizationURLResponse) ProtoMessage() {}

func (x *GetGithubAuthorizationURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_v1_oauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGithubAuthorizationURLResponse.ProtoReflect.Descriptor instead.
func (*GetGithubAuthorizationURLResponse) Descriptor() ([]byte, []int) {
	return file_oauth_v1_oauth_proto_rawDescGZIP(), []int{5}
}

func (x *GetGithubAuthorizationURLResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *GetGithubAuthorizationURLResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ExchangeGithubCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeGithubCodeRequest) Reset() {
	*x = ExchangeGithubCodeRequest{}
	mi := &file_oauth_v1_oauth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeGithubCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeGithubCodeRequest) ProtoMessage() {}

func (x *ExchangeGithubCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_v1_oauth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeGithubCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeGithubCodeRequest) Descriptor() ([]byte, []int) {
	return file_oauth_v1_oauth_proto_rawDescGZIP(), []int{6}
}

func (x *ExchangeGithubCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeGithubCodeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ExchangeGithubCodeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type ExchangeGithubCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocoToken     string                 `protobuf:"bytes,1,opt,name=loco_token,json=locoToken,proto3" json:"loco_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeGithubCodeResponse) Reset() {
	*x = ExchangeGithubCodeResponse{}
	mi := &file_oauth_v1_oauth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeGithubCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeGithubCodeResponse) ProtoMessage() {}

func (x *ExchangeGithubCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_v1_oauth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeGithubCodeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeGithubCodeResponse) Descriptor() ([]byte, []int) {
	return file_oauth_v1_oauth_proto_rawDescGZIP(), []int{7}
}

func (x *ExchangeGithubCodeResponse) GetLocoToken() string {
	if x != nil {
		return x.LocoToken
	}
	return ""
}

func (x *ExchangeGithubCodeResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *ExchangeGithubCodeResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExchangeGithubCodeResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_oauth_v1_oauth_proto protoreflect.FileDescriptor

const file_oauth_v1_oauth_proto_rawDesc = "" +
	"\n" +
	"\x14oauth/v1/oauth.proto\x12\rloco.oauth.v1\"\x1b\n" +
	"\x19GithubOAuthDetailsRequest\"V\n" +
	"\x1aGithubOAuthDetailsResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\ttoken_ttl\x18\x02 \x01(\x01R\btokenTtl\"\x86\x01\n" +
	"\x1aExchangeGithubTokenRequest\x12.\n" +
	"\x13github_access_token\x18\x01 \x01(\tR\x11githubAccessToken\x128\n" +
	"\x19create_user_if_not_exists\x18\x02 \x01(\bR\x15createUserIfNotExists\"\x90\x01\n" +
	"\x1bExchangeGithubTokenResponse\x12\x1d\n" +
	"\n" +
	"loco_token\x18\x01 \x01(\tR\tlocoToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"[\n" +
	" GetGithubAuthorizationURLRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\"f\n" +
	"!GetGithubAuthorizationURLResponse\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"h\n" +
	"\x19ExchangeGithubCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\"\x8f\x01\n" +
	"\x1aExchangeGithubCodeResponse\x12\x1d\n" +
	"\n" +
	"loco_token\x18\x01 \x01(\tR\tlocoToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername2\xd9\x03\n" +
	"\fOAuthService\x12k\n" +
	"\x12GithubOAuthDetails\x12(.loco.oauth.v1.GithubOAuthDetailsRequest\x1a).loco.oauth.v1.GithubOAuthDetailsResponse\"\x00\x12l\n" +
	"\x13ExchangeGithubToken\x12).loco.oauth.v1.ExchangeGithubTokenRequest\x1a*.loco.oauth.v1.ExchangeGithubTokenResponse\x12\x80\x01\n" +
	"\x19GetGithubAuthorizationURL\x12/.loco.oauth.v1.GetGithubAuthorizationURLRequest\x1a0.loco.oauth.v1.GetGithubAuthorizationURLResponse\"\x00\x12k\n" +
	"\x12ExchangeGithubCode\x12(.loco.oauth.v1.ExchangeGithubCodeRequest\x1a).loco.oauth.v1.ExchangeGithubCodeResponse\"\x00B9Z7github.com/loco-team/loco/shared/proto/oauth/v1;oauthv1b\x06proto3"

var (
	file_oauth_v1_oauth_proto_rawDescOnce sync.Once
	file_oauth_v1_oauth_proto_rawDescData []byte
)

func file_oauth_v1_oauth_proto_rawDescGZIP() []byte {
	file_oauth_v1_oauth_proto_rawDescOnce.Do(func() {
		file_oauth_v1_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauth_v1_oauth_proto_rawDesc), len(file_oauth_v1_oauth_proto_rawDesc)))
	})
	return file_oauth_v1_oauth_proto_rawDescData
}

var file_oauth_v1_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_oauth_v1_oauth_proto_goTypes = []any{
	(*GithubOAuthDetailsRequest)(nil),         // 0: loco.oauth.v1.GithubOAuthDetailsRequest
	(*GithubOAuthDetailsResponse)(nil),        // 1: loco.oauth.v1.GithubOAuthDetailsResponse
	(*ExchangeGithubTokenRequest)(nil),        // 2: loco.oauth.v1.ExchangeGithubTokenRequest
	(*ExchangeGithubTokenResponse)(nil),       // 3: loco.oauth.v1.ExchangeGithubTokenResponse
	(*GetGithubAuthorizationURLRequest)(nil),  // 4: loco.oauth.v1.GetGithubAuthorizationURLRequest
	(*GetGithubAuthorizationURLResponse)(nil), // 5: loco.oauth.v1.GetGithubAuthorizationURLResponse
	(*ExchangeGithubCodeRequest)(nil),         // 6: loco.oauth.v1.ExchangeGithubCodeRequest
	(*ExchangeGithubCodeResponse)(nil),        // 7: loco.oauth.v1.ExchangeGithubCodeResponse
}
var file_oauth_v1_oauth_proto_depIdxs = []int32{
	0, // 0: loco.oauth.v1.OAuthService.GithubOAuthDetails:input_type -> loco.oauth.v1.GithubOAuthDetailsRequest
	2, // 1: loco.oauth.v1.OAuthService.ExchangeGithubToken:input_type -> loco.oauth.v1.ExchangeGithubTokenRequest
	4, // 2: loco.oauth.v1.OAuthService.GetGithubAuthorizationURL:input_type -> loco.oauth.v1.GetGithubAuthorizationURLRequest
	6, // 3: loco.oauth.v1.OAuthService.ExchangeGithubCode:input_type -> loco.oauth.v1.ExchangeGithubCodeRequest
	1, // 4: loco.oauth.v1.OAuthService.GithubOAuthDetails:output_type -> loco.oauth.v1.GithubOAuthDetailsResponse
	3, // 5: loco.oauth.v1.OAuthService.ExchangeGithubToken:output_type -> loco.oauth.v1.ExchangeGithubTokenResponse
	5, // 6: loco.oauth.v1.OAuthService.GetGithubAuthorizationURL:output_type -> loco.oauth.v1.GetGithubAuthorizationURLResponse
	7, // 7: loco.oauth.v1.OAuthService.ExchangeGithubCode:output_type -> loco.oauth.v1.ExchangeGithubCodeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oauth_v1_oauth_proto_init() }
func file_oauth_v1_oauth_proto_init() {
	if File_oauth_v1_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauth_v1_oauth_proto_rawDesc), len(file_oauth_v1_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauth_v1_oauth_proto_goTypes,
		DependencyIndexes: file_oauth_v1_oauth_proto_depIdxs,
		MessageInfos:      file_oauth_v1_oauth_proto_msgTypes,
	}.Build()
	File_oauth_v1_oauth_proto = out.File
	file_oauth_v1_oauth_proto_goTypes = nil
	file_oauth_v1_oauth_proto_depIdxs = nil
}
