controller:
  image:
    pullPolicy: Never
registry:
  pullSecretName: loco-registry
builds:
  pushSecretName: loco-registry-push
  insecureRegistry: true
  timeout: 10m
  builderImage:
    pullPolicy: Never
  buildkitImage:
    pullPolicy: Never
