{{- if .Values.builds.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        {{- include "loco-operator.buildControllerLabels" . | nindent 8 }}
    name: loco-build-controller
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: loco-build-controller
subjects:
    - kind: ServiceAccount
      name: loco-build-controller
      namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        {{- include "loco-operator.buildControllerLabels" . | nindent 8 }}
    name: loco-build-controller
    namespace: {{ .Values.builds.namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: loco-build-controller
subjects:
    - kind: ServiceAccount
      name: loco-build-controller
      namespace: {{ .Release.Namespace }}
{{- end }}
