{{- if .Values.builds.enabled }}
{{- $secrets := compact (list .Values.builds.pushSecretName .Values.registry.pullSecretName) }}
{{- if $secrets }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    labels:
        {{- include "loco-operator.buildControllerLabels" . | nindent 8 }}
    name: loco-build-controller-registry-secrets
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups:
        - ""
      resources:
        - secrets
      resourceNames:
        {{- toYaml $secrets | nindent 8 }}
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        {{- include "loco-operator.buildControllerLabels" . | nindent 8 }}
    name: loco-build-controller-registry-secrets
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: loco-build-controller-registry-secrets
subjects:
    - kind: ServiceAccount
      name: loco-build-controller
      namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
