{{- if .Values.builds.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        {{- include "loco-operator.buildControllerLabels" . | nindent 8 }}
    name: loco-build-controller
    namespace: {{ .Release.Namespace }}
{{- end }}
