// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: domain/v1/domain.proto

package domainv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainType int32

const (
	DomainType_PLATFORM_PROVIDED DomainType = 0
	DomainType_USER_PROVIDED     DomainType = 1
)

// Enum value maps for DomainType.
var (
	DomainType_name = map[int32]string{
		0: "PLATFORM_PROVIDED",
		1: "USER_PROVIDED",
	}
	DomainType_value = map[string]int32{
		"PLATFORM_PROVIDED": 0,
		"USER_PROVIDED":     1,
	}
)

func (x DomainType) Enum() *DomainType {
	p := new(DomainType)
	*p = x
	return p
}

func (x DomainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_v1_domain_proto_enumTypes[0].Descriptor()
}

func (DomainType) Type() protoreflect.EnumType {
	return &file_domain_v1_domain_proto_enumTypes[0]
}

func (x DomainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainType.Descriptor instead.
func (DomainType) EnumDescriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{0}
}

// PlatformDomain represents a platform-provided domain.
type PlatformDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformDomain) Reset() {
	*x = PlatformDomain{}
	mi := &file_domain_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformDomain) ProtoMessage() {}

func (x *PlatformDomain) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformDomain.ProtoReflect.Descriptor instead.
func (*PlatformDomain) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformDomain) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlatformDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PlatformDomain) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PlatformDomain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlatformDomain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DomainInput specifies domain configuration for an application.
type DomainInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DomainSource     DomainType             `protobuf:"varint,1,opt,name=domain_source,json=domainSource,proto3,enum=loco.domain.v1.DomainType" json:"domain_source,omitempty"`
	Subdomain        *string                `protobuf:"bytes,2,opt,name=subdomain,proto3,oneof" json:"subdomain,omitempty"`                                          // for PLATFORM_PROVIDED: "myapp"
	PlatformDomainId *int64                 `protobuf:"varint,3,opt,name=platform_domain_id,json=platformDomainId,proto3,oneof" json:"platform_domain_id,omitempty"` // for PLATFORM_PROVIDED: id of the platform domain
	Domain           *string                `protobuf:"bytes,4,opt,name=domain,proto3,oneof" json:"domain,omitempty"`                                                // for USER_PROVIDED: full custom domain
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DomainInput) Reset() {
	*x = DomainInput{}
	mi := &file_domain_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainInput) ProtoMessage() {}

func (x *DomainInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainInput.ProtoReflect.Descriptor instead.
func (*DomainInput) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *DomainInput) GetDomainSource() DomainType {
	if x != nil {
		return x.DomainSource
	}
	return DomainType_PLATFORM_PROVIDED
}

func (x *DomainInput) GetSubdomain() string {
	if x != nil && x.Subdomain != nil {
		return *x.Subdomain
	}
	return ""
}

func (x *DomainInput) GetPlatformDomainId() int64 {
	if x != nil && x.PlatformDomainId != nil {
		return *x.PlatformDomainId
	}
	return 0
}

func (x *DomainInput) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

// AppDomain represents a domain assigned to an application.
type AppDomain struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId            int64                  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Domain           string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	DomainSource     DomainType             `protobuf:"varint,4,opt,name=domain_source,json=domainSource,proto3,enum=loco.domain.v1.DomainType" json:"domain_source,omitempty"`
	SubdomainLabel   *string                `protobuf:"bytes,5,opt,name=subdomain_label,json=subdomainLabel,proto3,oneof" json:"subdomain_label,omitempty"`
	PlatformDomainId *int64                 `protobuf:"varint,6,opt,name=platform_domain_id,json=platformDomainId,proto3,oneof" json:"platform_domain_id,omitempty"`
	IsPrimary        bool                   `protobuf:"varint,7,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AppDomain) Reset() {
	*x = AppDomain{}
	mi := &file_domain_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDomain) ProtoMessage() {}

func (x *AppDomain) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDomain.ProtoReflect.Descriptor instead.
func (*AppDomain) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{2}
}

func (x *AppDomain) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppDomain) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AppDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AppDomain) GetDomainSource() DomainType {
	if x != nil {
		return x.DomainSource
	}
	return DomainType_PLATFORM_PROVIDED
}

func (x *AppDomain) GetSubdomainLabel() string {
	if x != nil && x.SubdomainLabel != nil {
		return *x.SubdomainLabel
	}
	return ""
}

func (x *AppDomain) GetPlatformDomainId() int64 {
	if x != nil && x.PlatformDomainId != nil {
		return *x.PlatformDomainId
	}
	return 0
}

func (x *AppDomain) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *AppDomain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppDomain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreatePlatformDomainRequest is the request to create a platform domain.
type CreatePlatformDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlatformDomainRequest) Reset() {
	*x = CreatePlatformDomainRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlatformDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlatformDomainRequest) ProtoMessage() {}

func (x *CreatePlatformDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlatformDomainRequest.ProtoReflect.Descriptor instead.
func (*CreatePlatformDomainRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePlatformDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreatePlatformDomainRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// CreatePlatformDomainResponse is the response from creating a platform domain.
type CreatePlatformDomainResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformDomain *PlatformDomain        `protobuf:"bytes,1,opt,name=platform_domain,json=platformDomain,proto3" json:"platform_domain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePlatformDomainResponse) Reset() {
	*x = CreatePlatformDomainResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlatformDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlatformDomainResponse) ProtoMessage() {}

func (x *CreatePlatformDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlatformDomainResponse.ProtoReflect.Descriptor instead.
func (*CreatePlatformDomainResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePlatformDomainResponse) GetPlatformDomain() *PlatformDomain {
	if x != nil {
		return x.PlatformDomain
	}
	return nil
}

// GetPlatformDomainRequest is the request to retrieve a platform domain.
type GetPlatformDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformDomainRequest) Reset() {
	*x = GetPlatformDomainRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformDomainRequest) ProtoMessage() {}

func (x *GetPlatformDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformDomainRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformDomainRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlatformDomainRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetPlatformDomainResponse is the response containing platform domain information.
type GetPlatformDomainResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformDomain *PlatformDomain        `protobuf:"bytes,1,opt,name=platform_domain,json=platformDomain,proto3" json:"platform_domain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPlatformDomainResponse) Reset() {
	*x = GetPlatformDomainResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformDomainResponse) ProtoMessage() {}

func (x *GetPlatformDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformDomainResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformDomainResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlatformDomainResponse) GetPlatformDomain() *PlatformDomain {
	if x != nil {
		return x.PlatformDomain
	}
	return nil
}

// GetPlatformDomainByNameRequest is the request to retrieve a platform domain by name.
type GetPlatformDomainByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformDomainByNameRequest) Reset() {
	*x = GetPlatformDomainByNameRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformDomainByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformDomainByNameRequest) ProtoMessage() {}

func (x *GetPlatformDomainByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformDomainByNameRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformDomainByNameRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlatformDomainByNameRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// GetPlatformDomainByNameResponse is the response containing the platform domain.
type GetPlatformDomainByNameResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformDomain *PlatformDomain        `protobuf:"bytes,1,opt,name=platform_domain,json=platformDomain,proto3" json:"platform_domain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPlatformDomainByNameResponse) Reset() {
	*x = GetPlatformDomainByNameResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformDomainByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformDomainByNameResponse) ProtoMessage() {}

func (x *GetPlatformDomainByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformDomainByNameResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformDomainByNameResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlatformDomainByNameResponse) GetPlatformDomain() *PlatformDomain {
	if x != nil {
		return x.PlatformDomain
	}
	return nil
}

// ListActivePlatformDomainsRequest is the request to list active platform domains.
type ListActivePlatformDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivePlatformDomainsRequest) Reset() {
	*x = ListActivePlatformDomainsRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivePlatformDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivePlatformDomainsRequest) ProtoMessage() {}

func (x *ListActivePlatformDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivePlatformDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListActivePlatformDomainsRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{9}
}

// ListActivePlatformDomainsResponse contains the list of active platform domains.
type ListActivePlatformDomainsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlatformDomains []*PlatformDomain      `protobuf:"bytes,1,rep,name=platform_domains,json=platformDomains,proto3" json:"platform_domains,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListActivePlatformDomainsResponse) Reset() {
	*x = ListActivePlatformDomainsResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivePlatformDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivePlatformDomainsResponse) ProtoMessage() {}

func (x *ListActivePlatformDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivePlatformDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListActivePlatformDomainsResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{10}
}

func (x *ListActivePlatformDomainsResponse) GetPlatformDomains() []*PlatformDomain {
	if x != nil {
		return x.PlatformDomains
	}
	return nil
}

// DeactivatePlatformDomainRequest is the request to deactivate a platform domain.
type DeactivatePlatformDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivatePlatformDomainRequest) Reset() {
	*x = DeactivatePlatformDomainRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivatePlatformDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivatePlatformDomainRequest) ProtoMessage() {}

func (x *DeactivatePlatformDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivatePlatformDomainRequest.ProtoReflect.Descriptor instead.
func (*DeactivatePlatformDomainRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{11}
}

func (x *DeactivatePlatformDomainRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeactivatePlatformDomainResponse is the response from deactivating a platform domain.
type DeactivatePlatformDomainResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformDomain *PlatformDomain        `protobuf:"bytes,1,opt,name=platform_domain,json=platformDomain,proto3" json:"platform_domain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeactivatePlatformDomainResponse) Reset() {
	*x = DeactivatePlatformDomainResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivatePlatformDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivatePlatformDomainResponse) ProtoMessage() {}

func (x *DeactivatePlatformDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivatePlatformDomainResponse.ProtoReflect.Descriptor instead.
func (*DeactivatePlatformDomainResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{12}
}

func (x *DeactivatePlatformDomainResponse) GetPlatformDomain() *PlatformDomain {
	if x != nil {
		return x.PlatformDomain
	}
	return nil
}

// CheckDomainAvailabilityRequest is the request to check domain availability.
type CheckDomainAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDomainAvailabilityRequest) Reset() {
	*x = CheckDomainAvailabilityRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDomainAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDomainAvailabilityRequest) ProtoMessage() {}

func (x *CheckDomainAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDomainAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckDomainAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{13}
}

func (x *CheckDomainAvailabilityRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// CheckDomainAvailabilityResponse indicates if a domain is available.
type CheckDomainAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDomainAvailabilityResponse) Reset() {
	*x = CheckDomainAvailabilityResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDomainAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDomainAvailabilityResponse) ProtoMessage() {}

func (x *CheckDomainAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDomainAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckDomainAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{14}
}

func (x *CheckDomainAvailabilityResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

// LocoOwnedDomain represents a domain with an associated application.
type LocoOwnedDomain struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain         string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	AppName        string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppId          int64                  `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	PlatformDomain string                 `protobuf:"bytes,5,opt,name=platform_domain,json=platformDomain,proto3" json:"platform_domain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocoOwnedDomain) Reset() {
	*x = LocoOwnedDomain{}
	mi := &file_domain_v1_domain_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocoOwnedDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocoOwnedDomain) ProtoMessage() {}

func (x *LocoOwnedDomain) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocoOwnedDomain.ProtoReflect.Descriptor instead.
func (*LocoOwnedDomain) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{15}
}

func (x *LocoOwnedDomain) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LocoOwnedDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LocoOwnedDomain) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *LocoOwnedDomain) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *LocoOwnedDomain) GetPlatformDomain() string {
	if x != nil {
		return x.PlatformDomain
	}
	return ""
}

// ListAllLocoOwnedDomainsRequest is the request to list all Loco-owned domains.
type ListAllLocoOwnedDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllLocoOwnedDomainsRequest) Reset() {
	*x = ListAllLocoOwnedDomainsRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllLocoOwnedDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllLocoOwnedDomainsRequest) ProtoMessage() {}

func (x *ListAllLocoOwnedDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllLocoOwnedDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListAllLocoOwnedDomainsRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{16}
}

// ListAllLocoOwnedDomainsResponse contains the list of Loco-owned domains.
type ListAllLocoOwnedDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*LocoOwnedDomain     `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllLocoOwnedDomainsResponse) Reset() {
	*x = ListAllLocoOwnedDomainsResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllLocoOwnedDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllLocoOwnedDomainsResponse) ProtoMessage() {}

func (x *ListAllLocoOwnedDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllLocoOwnedDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListAllLocoOwnedDomainsResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{17}
}

func (x *ListAllLocoOwnedDomainsResponse) GetDomains() []*LocoOwnedDomain {
	if x != nil {
		return x.Domains
	}
	return nil
}

// AddAppDomainRequest is the request to add a domain to an application.
type AddAppDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Domain        *DomainInput           `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppDomainRequest) Reset() {
	*x = AddAppDomainRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppDomainRequest) ProtoMessage() {}

func (x *AddAppDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppDomainRequest.ProtoReflect.Descriptor instead.
func (*AddAppDomainRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{18}
}

func (x *AddAppDomainRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AddAppDomainRequest) GetDomain() *DomainInput {
	if x != nil {
		return x.Domain
	}
	return nil
}

// AddAppDomainResponse is the response from adding a domain to an application.
type AddAppDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *AppDomain             `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppDomainResponse) Reset() {
	*x = AddAppDomainResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppDomainResponse) ProtoMessage() {}

func (x *AddAppDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppDomainResponse.ProtoReflect.Descriptor instead.
func (*AddAppDomainResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{19}
}

func (x *AddAppDomainResponse) GetDomain() *AppDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *AddAppDomainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateAppDomainRequest is the request to update an application's domain.
type UpdateAppDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      int64                  `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppDomainRequest) Reset() {
	*x = UpdateAppDomainRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppDomainRequest) ProtoMessage() {}

func (x *UpdateAppDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppDomainRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppDomainRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateAppDomainRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *UpdateAppDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// UpdateAppDomainResponse is the response from updating an application's domain.
type UpdateAppDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *AppDomain             `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppDomainResponse) Reset() {
	*x = UpdateAppDomainResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppDomainResponse) ProtoMessage() {}

func (x *UpdateAppDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppDomainResponse.ProtoReflect.Descriptor instead.
func (*UpdateAppDomainResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateAppDomainResponse) GetDomain() *AppDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *UpdateAppDomainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SetPrimaryAppDomainRequest is the request to set the primary domain for an application.
type SetPrimaryAppDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DomainId      int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPrimaryAppDomainRequest) Reset() {
	*x = SetPrimaryAppDomainRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrimaryAppDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrimaryAppDomainRequest) ProtoMessage() {}

func (x *SetPrimaryAppDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrimaryAppDomainRequest.ProtoReflect.Descriptor instead.
func (*SetPrimaryAppDomainRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{22}
}

func (x *SetPrimaryAppDomainRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *SetPrimaryAppDomainRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

// SetPrimaryAppDomainResponse is the response from setting the primary domain.
type SetPrimaryAppDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *AppDomain             `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPrimaryAppDomainResponse) Reset() {
	*x = SetPrimaryAppDomainResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrimaryAppDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrimaryAppDomainResponse) ProtoMessage() {}

func (x *SetPrimaryAppDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrimaryAppDomainResponse.ProtoReflect.Descriptor instead.
func (*SetPrimaryAppDomainResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{23}
}

func (x *SetPrimaryAppDomainResponse) GetDomain() *AppDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *SetPrimaryAppDomainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RemoveAppDomainRequest is the request to remove a domain from an application.
type RemoveAppDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      int64                  `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAppDomainRequest) Reset() {
	*x = RemoveAppDomainRequest{}
	mi := &file_domain_v1_domain_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAppDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAppDomainRequest) ProtoMessage() {}

func (x *RemoveAppDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAppDomainRequest.ProtoReflect.Descriptor instead.
func (*RemoveAppDomainRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveAppDomainRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

// RemoveAppDomainResponse is the response from removing a domain.
type RemoveAppDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAppDomainResponse) Reset() {
	*x = RemoveAppDomainResponse{}
	mi := &file_domain_v1_domain_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAppDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAppDomainResponse) ProtoMessage() {}

func (x *RemoveAppDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_domain_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAppDomainResponse.ProtoReflect.Descriptor instead.
func (*RemoveAppDomainResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_domain_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveAppDomainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_domain_v1_domain_proto protoreflect.FileDescriptor

const file_domain_v1_domain_proto_rawDesc = "" +
	"\n" +
	"\x16domain/v1/domain.proto\x12\x0eloco.domain.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x01\n" +
	"\x0ePlatformDomain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf1\x01\n" +
	"\vDomainInput\x12?\n" +
	"\rdomain_source\x18\x01 \x01(\x0e2\x1a.loco.domain.v1.DomainTypeR\fdomainSource\x12!\n" +
	"\tsubdomain\x18\x02 \x01(\tH\x00R\tsubdomain\x88\x01\x01\x121\n" +
	"\x12platform_domain_id\x18\x03 \x01(\x03H\x01R\x10platformDomainId\x88\x01\x01\x12\x1b\n" +
	"\x06domain\x18\x04 \x01(\tH\x02R\x06domain\x88\x01\x01B\f\n" +
	"\n" +
	"_subdomainB\x15\n" +
	"\x13_platform_domain_idB\t\n" +
	"\a_domain\"\xac\x03\n" +
	"\tAppDomain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\x03R\x05appId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12?\n" +
	"\rdomain_source\x18\x04 \x01(\x0e2\x1a.loco.domain.v1.DomainTypeR\fdomainSource\x12,\n" +
	"\x0fsubdomain_label\x18\x05 \x01(\tH\x00R\x0esubdomainLabel\x88\x01\x01\x121\n" +
	"\x12platform_domain_id\x18\x06 \x01(\x03H\x01R\x10platformDomainId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_primary\x18\a \x01(\bR\tisPrimary\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x12\n" +
	"\x10_subdomain_labelB\x15\n" +
	"\x13_platform_domain_id\"R\n" +
	"\x1bCreatePlatformDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\"g\n" +
	"\x1cCreatePlatformDomainResponse\x12G\n" +
	"\x0fplatform_domain\x18\x01 \x01(\v2\x1e.loco.domain.v1.PlatformDomainR\x0eplatformDomain\"*\n" +
	"\x18GetPlatformDomainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"d\n" +
	"\x19GetPlatformDomainResponse\x12G\n" +
	"\x0fplatform_domain\x18\x01 \x01(\v2\x1e.loco.domain.v1.PlatformDomainR\x0eplatformDomain\"8\n" +
	"\x1eGetPlatformDomainByNameRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"j\n" +
	"\x1fGetPlatformDomainByNameResponse\x12G\n" +
	"\x0fplatform_domain\x18\x01 \x01(\v2\x1e.loco.domain.v1.PlatformDomainR\x0eplatformDomain\"\"\n" +
	" ListActivePlatformDomainsRequest\"n\n" +
	"!ListActivePlatformDomainsResponse\x12I\n" +
	"\x10platform_domains\x18\x01 \x03(\v2\x1e.loco.domain.v1.PlatformDomainR\x0fplatformDomains\"1\n" +
	"\x1fDeactivatePlatformDomainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"k\n" +
	" DeactivatePlatformDomainResponse\x12G\n" +
	"\x0fplatform_domain\x18\x01 \x01(\v2\x1e.loco.domain.v1.PlatformDomainR\x0eplatformDomain\"8\n" +
	"\x1eCheckDomainAvailabilityRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"D\n" +
	"\x1fCheckDomainAvailabilityResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\"\x94\x01\n" +
	"\x0fLocoOwnedDomain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\x03R\x05appId\x12'\n" +
	"\x0fplatform_domain\x18\x05 \x01(\tR\x0eplatformDomain\" \n" +
	"\x1eListAllLocoOwnedDomainsRequest\"\\\n" +
	"\x1fListAllLocoOwnedDomainsResponse\x129\n" +
	"\adomains\x18\x01 \x03(\v2\x1f.loco.domain.v1.LocoOwnedDomainR\adomains\"a\n" +
	"\x13AddAppDomainRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\x123\n" +
	"\x06domain\x18\x02 \x01(\v2\x1b.loco.domain.v1.DomainInputR\x06domain\"c\n" +
	"\x14AddAppDomainResponse\x121\n" +
	"\x06domain\x18\x01 \x01(\v2\x19.loco.domain.v1.AppDomainR\x06domain\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x16UpdateAppDomainRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\x03R\bdomainId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"f\n" +
	"\x17UpdateAppDomainResponse\x121\n" +
	"\x06domain\x18\x01 \x01(\v2\x19.loco.domain.v1.AppDomainR\x06domain\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"P\n" +
	"\x1aSetPrimaryAppDomainRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\"j\n" +
	"\x1bSetPrimaryAppDomainResponse\x121\n" +
	"\x06domain\x18\x01 \x01(\v2\x19.loco.domain.v1.AppDomainR\x06domain\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x16RemoveAppDomainRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\x03R\bdomainId\"3\n" +
	"\x17RemoveAppDomainResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*6\n" +
	"\n" +
	"DomainType\x12\x15\n" +
	"\x11PLATFORM_PROVIDED\x10\x00\x12\x11\n" +
	"\rUSER_PROVIDED\x10\x012\xf5\t\n" +
	"\rDomainService\x12q\n" +
	"\x14CreatePlatformDomain\x12+.loco.domain.v1.CreatePlatformDomainRequest\x1a,.loco.domain.v1.CreatePlatformDomainResponse\x12h\n" +
	"\x11GetPlatformDomain\x12(.loco.domain.v1.GetPlatformDomainRequest\x1a).loco.domain.v1.GetPlatformDomainResponse\x12z\n" +
	"\x17GetPlatformDomainByName\x12..loco.domain.v1.GetPlatformDomainByNameRequest\x1a/.loco.domain.v1.GetPlatformDomainByNameResponse\x12\x80\x01\n" +
	"\x19ListActivePlatformDomains\x120.loco.domain.v1.ListActivePlatformDomainsRequest\x1a1.loco.domain.v1.ListActivePlatformDomainsResponse\x12}\n" +
	"\x18DeactivatePlatformDomain\x12/.loco.domain.v1.DeactivatePlatformDomainRequest\x1a0.loco.domain.v1.DeactivatePlatformDomainResponse\x12Y\n" +
	"\fAddAppDomain\x12#.loco.domain.v1.AddAppDomainRequest\x1a$.loco.domain.v1.AddAppDomainResponse\x12b\n" +
	"\x0fUpdateAppDomain\x12&.loco.domain.v1.UpdateAppDomainRequest\x1a'.loco.domain.v1.UpdateAppDomainResponse\x12n\n" +
	"\x13SetPrimaryAppDomain\x12*.loco.domain.v1.SetPrimaryAppDomainRequest\x1a+.loco.domain.v1.SetPrimaryAppDomainResponse\x12b\n" +
	"\x0fRemoveAppDomain\x12&.loco.domain.v1.RemoveAppDomainRequest\x1a'.loco.domain.v1.RemoveAppDomainResponse\x12z\n" +
	"\x17CheckDomainAvailability\x12..loco.domain.v1.CheckDomainAvailabilityRequest\x1a/.loco.domain.v1.CheckDomainAvailabilityResponse\x12z\n" +
	"\x17ListAllLocoOwnedDomains\x12..loco.domain.v1.ListAllLocoOwnedDomainsRequest\x1a/.loco.domain.v1.ListAllLocoOwnedDomainsResponseB;Z9github.com/loco-team/loco/shared/proto/domain/v1;domainv1b\x06proto3"

var (
	file_domain_v1_domain_proto_rawDescOnce sync.Once
	file_domain_v1_domain_proto_rawDescData []byte
)

func file_domain_v1_domain_proto_rawDescGZIP() []byte {
	file_domain_v1_domain_proto_rawDescOnce.Do(func() {
		file_domain_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_v1_domain_proto_rawDesc), len(file_domain_v1_domain_proto_rawDesc)))
	})
	return file_domain_v1_domain_proto_rawDescData
}

var file_domain_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_domain_v1_domain_proto_goTypes = []any{
	(DomainType)(0),                           // 0: loco.domain.v1.DomainType
	(*PlatformDomain)(nil),                    // 1: loco.domain.v1.PlatformDomain
	(*DomainInput)(nil),                       // 2: loco.domain.v1.DomainInput
	(*AppDomain)(nil),                         // 3: loco.domain.v1.AppDomain
	(*CreatePlatformDomainRequest)(nil),       // 4: loco.domain.v1.CreatePlatformDomainRequest
	(*CreatePlatformDomainResponse)(nil),      // 5: loco.domain.v1.CreatePlatformDomainResponse
	(*GetPlatformDomainRequest)(nil),          // 6: loco.domain.v1.GetPlatformDomainRequest
	(*GetPlatformDomainResponse)(nil),         // 7: loco.domain.v1.GetPlatformDomainResponse
	(*GetPlatformDomainByNameRequest)(nil),    // 8: loco.domain.v1.GetPlatformDomainByNameRequest
	(*GetPlatformDomainByNameResponse)(nil),   // 9: loco.domain.v1.GetPlatformDomainByNameResponse
	(*ListActivePlatformDomainsRequest)(nil),  // 10: loco.domain.v1.ListActivePlatformDomainsRequest
	(*ListActivePlatformDomainsResponse)(nil), // 11: loco.domain.v1.ListActivePlatformDomainsResponse
	(*DeactivatePlatformDomainRequest)(nil),   // 12: loco.domain.v1.DeactivatePlatformDomainRequest
	(*DeactivatePlatformDomainResponse)(nil),  // 13: loco.domain.v1.DeactivatePlatformDomainResponse
	(*CheckDomainAvailabilityRequest)(nil),    // 14: loco.domain.v1.CheckDomainAvailabilityRequest
	(*CheckDomainAvailabilityResponse)(nil),   // 15: loco.domain.v1.CheckDomainAvailabilityResponse
	(*LocoOwnedDomain)(nil),                   // 16: loco.domain.v1.LocoOwnedDomain
	(*ListAllLocoOwnedDomainsRequest)(nil),    // 17: loco.domain.v1.ListAllLocoOwnedDomainsRequest
	(*ListAllLocoOwnedDomainsResponse)(nil),   // 18: loco.domain.v1.ListAllLocoOwnedDomainsResponse
	(*AddAppDomainRequest)(nil),               // 19: loco.domain.v1.AddAppDomainRequest
	(*AddAppDomainResponse)(nil),              // 20: loco.domain.v1.AddAppDomainResponse
	(*UpdateAppDomainRequest)(nil),            // 21: loco.domain.v1.UpdateAppDomainRequest
	(*UpdateAppDomainResponse)(nil),           // 22: loco.domain.v1.UpdateAppDomainResponse
	(*SetPrimaryAppDomainRequest)(nil),        // 23: loco.domain.v1.SetPrimaryAppDomainRequest
	(*SetPrimaryAppDomainResponse)(nil),       // 24: loco.domain.v1.SetPrimaryAppDomainResponse
	(*RemoveAppDomainRequest)(nil),            // 25: loco.domain.v1.RemoveAppDomainRequest
	(*RemoveAppDomainResponse)(nil),           // 26: loco.domain.v1.RemoveAppDomainResponse
	(*timestamppb.Timestamp)(nil),             // 27: google.protobuf.Timestamp
}
var file_domain_v1_domain_proto_depIdxs = []int32{
	27, // 0: loco.domain.v1.PlatformDomain.created_at:type_name -> google.protobuf.Timestamp
	27, // 1: loco.domain.v1.PlatformDomain.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: loco.domain.v1.DomainInput.domain_source:type_name -> loco.domain.v1.DomainType
	0,  // 3: loco.domain.v1.AppDomain.domain_source:type_name -> loco.domain.v1.DomainType
	27, // 4: loco.domain.v1.AppDomain.created_at:type_name -> google.protobuf.Timestamp
	27, // 5: loco.domain.v1.AppDomain.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: loco.domain.v1.CreatePlatformDomainResponse.platform_domain:type_name -> loco.domain.v1.PlatformDomain
	1,  // 7: loco.domain.v1.GetPlatformDomainResponse.platform_domain:type_name -> loco.domain.v1.PlatformDomain
	1,  // 8: loco.domain.v1.GetPlatformDomainByNameResponse.platform_domain:type_name -> loco.domain.v1.PlatformDomain
	1,  // 9: loco.domain.v1.ListActivePlatformDomainsResponse.platform_domains:type_name -> loco.domain.v1.PlatformDomain
	1,  // 10: loco.domain.v1.DeactivatePlatformDomainResponse.platform_domain:type_name -> loco.domain.v1.PlatformDomain
	16, // 11: loco.domain.v1.ListAllLocoOwnedDomainsResponse.domains:type_name -> loco.domain.v1.LocoOwnedDomain
	2,  // 12: loco.domain.v1.AddAppDomainRequest.domain:type_name -> loco.domain.v1.DomainInput
	3,  // 13: loco.domain.v1.AddAppDomainResponse.domain:type_name -> loco.domain.v1.AppDomain
	3,  // 14: loco.domain.v1.UpdateAppDomainResponse.domain:type_name -> loco.domain.v1.AppDomain
	3,  // 15: loco.domain.v1.SetPrimaryAppDomainResponse.domain:type_name -> loco.domain.v1.AppDomain
	4,  // 16: loco.domain.v1.DomainService.CreatePlatformDomain:input_type -> loco.domain.v1.CreatePlatformDomainRequest
	6,  // 17: loco.domain.v1.DomainService.GetPlatformDomain:input_type -> loco.domain.v1.GetPlatformDomainRequest
	8,  // 18: loco.domain.v1.DomainService.GetPlatformDomainByName:input_type -> loco.domain.v1.GetPlatformDomainByNameRequest
	10, // 19: loco.domain.v1.DomainService.ListActivePlatformDomains:input_type -> loco.domain.v1.ListActivePlatformDomainsRequest
	12, // 20: loco.domain.v1.DomainService.DeactivatePlatformDomain:input_type -> loco.domain.v1.DeactivatePlatformDomainRequest
	19, // 21: loco.domain.v1.DomainService.AddAppDomain:input_type -> loco.domain.v1.AddAppDomainRequest
	21, // 22: loco.domain.v1.DomainService.UpdateAppDomain:input_type -> loco.domain.v1.UpdateAppDomainRequest
	23, // 23: loco.domain.v1.DomainService.SetPrimaryAppDomain:input_type -> loco.domain.v1.SetPrimaryAppDomainRequest
	25, // 24: loco.domain.v1.DomainService.RemoveAppDomain:input_type -> loco.domain.v1.RemoveAppDomainRequest
	14, // 25: loco.domain.v1.DomainService.CheckDomainAvailability:input_type -> loco.domain.v1.CheckDomainAvailabilityRequest
	17, // 26: loco.domain.v1.DomainService.ListAllLocoOwnedDomains:input_type -> loco.domain.v1.ListAllLocoOwnedDomainsRequest
	5,  // 27: loco.domain.v1.DomainService.CreatePlatformDomain:output_type -> loco.domain.v1.CreatePlatformDomainResponse
	7,  // 28: loco.domain.v1.DomainService.GetPlatformDomain:output_type -> loco.domain.v1.GetPlatformDomainResponse
	9,  // 29: loco.domain.v1.DomainService.GetPlatformDomainByName:output_type -> loco.domain.v1.GetPlatformDomainByNameResponse
	11, // 30: loco.domain.v1.DomainService.ListActivePlatformDomains:output_type -> loco.domain.v1.ListActivePlatformDomainsResponse
	13, // 31: loco.domain.v1.DomainService.DeactivatePlatformDomain:output_type -> loco.domain.v1.DeactivatePlatformDomainResponse
	20, // 32: loco.domain.v1.DomainService.AddAppDomain:output_type -> loco.domain.v1.AddAppDomainResponse
	22, // 33: loco.domain.v1.DomainService.UpdateAppDomain:output_type -> loco.domain.v1.UpdateAppDomainResponse
	24, // 34: loco.domain.v1.DomainService.SetPrimaryAppDomain:output_type -> loco.domain.v1.SetPrimaryAppDomainResponse
	26, // 35: loco.domain.v1.DomainService.RemoveAppDomain:output_type -> loco.domain.v1.RemoveAppDomainResponse
	15, // 36: loco.domain.v1.DomainService.CheckDomainAvailability:output_type -> loco.domain.v1.CheckDomainAvailabilityResponse
	18, // 37: loco.domain.v1.DomainService.ListAllLocoOwnedDomains:output_type -> loco.domain.v1.ListAllLocoOwnedDomainsResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_domain_v1_domain_proto_init() }
func file_domain_v1_domain_proto_init() {
	if File_domain_v1_domain_proto != nil {
		return
	}
	file_domain_v1_domain_proto_msgTypes[1].OneofWrappers = []any{}
	file_domain_v1_domain_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_domain_proto_rawDesc), len(file_domain_v1_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_v1_domain_proto_goTypes,
		DependencyIndexes: file_domain_v1_domain_proto_depIdxs,
		EnumInfos:         file_domain_v1_domain_proto_enumTypes,
		MessageInfos:      file_domain_v1_domain_proto_msgTypes,
	}.Build()
	File_domain_v1_domain_proto = out.File
	file_domain_v1_domain_proto_goTypes = nil
	file_domain_v1_domain_proto_depIdxs = nil
}
