{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    pod-security.kubernetes.io/enforce: {{ .podSecurity }}
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: {{ .podSecurity }}
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: {{ .podSecurity }}
    pod-security.kubernetes.io/warn-version: latest
{{- end }}
