apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
rules:
  # Permissions for managing Application CRDs in the namespace
  - apiGroups: ["infra.loco.io"]
    resources: ["applications"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Permissions for reading status of Applications
  - apiGroups: ["infra.loco.io"]
    resources: ["applications/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-agent
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-agent
    namespace: {{ .Release.Namespace }}
