apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: {{ .Release.Name }}-cert
    namespace: {{ .Release.Namespace }}
spec:
    secretName: {{ .Release.Name }}-tls
    issuerRef:
        name: {{ .Values.certManager.issuer.name }}
        kind: ClusterIssuer
    {{- $primary := index .Values.global.domain.apps 0 }}
    commonName: {{ printf "*.%s" $primary | quote }}
    dnsNames:
        {{- range .Values.global.domain.apps }}
        - {{ printf "*.%s" . | quote }}
        {{- end }}
        - {{ printf "*.%s" .Values.global.domain.platform | quote }}
        - "*.us-east-1.{{ $primary }}"
        - "*.eu-west-1.{{ $primary }}"
        - "*.staging.us-east-1.{{ $primary }}"
        - "*.prod.us-east-1.{{ $primary }}"
        - "*.staging.eu-west-1.{{ $primary }}"
        - "*.prod.eu-west-1.{{ $primary }}"
