controller:
  replicas: 1

  image:
    repository: ghcr.io/team-loco/loco-controller
    tag: ""
    pullPolicy: Always

  args:
    - --leader-elect

  env: []

  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

registry:
  pullSecretName: ""

builds:
  enabled: true
  createNamespace: true

  controller:
    replicas: 1
    args:
      - --leader-elect
    env: []
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

  namespace: loco-builds
  podSecurity:
    level: privileged
    version: latest

  agentServiceAccount:
    name: loco-core-agent
    namespace: ""

  pushSecretName: ""
  builderImage:
    repository: ghcr.io/team-loco/loco-builder
    tag: ""
    pullPolicy: Always
  buildkitImage:
    repository: moby/buildkit
    tag: v0.34.0-rootless
    pullPolicy: IfNotPresent
  timeout: 30m
  ttlAfterFinished: 10m
  downloadTimeout: 10m
  maxSourceSize: 200Mi
  maxContextSize: 1Gi
  maxContextFiles: 200000
  maxImageSize: 1Gi
  insecureRegistry: false
  privateEgressCIDRs: []
  seccompLocalhostProfile: ""
  runtimeClassName: ""
  nodeSelector: {}
  tolerations: []
  resources:
    fetch:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: "1"
        memory: 256Mi
    build:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 4Gi
    push:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: "1"
        memory: 512Mi
  storage:
    workspace: 2Gi
    cache: 5Gi
    out: 10Gi
    buildkit: 10Gi

rbacHelpers:
  enable: false

crd:
  enable: true
  keep: true

metrics:
  enable: true
  port: 8443

certManager:
  enable: false

prometheus:
  enable: false
