// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: loco/observability/v1/observability_access.proto

package observabilityv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetObservabilityAccessRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Optional: restrict to specific resources. Empty means all resources in workspace.
	ResourceIds   []string `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservabilityAccessRequest) Reset() {
	*x = GetObservabilityAccessRequest{}
	mi := &file_loco_observability_v1_observability_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservabilityAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservabilityAccessRequest) ProtoMessage() {}

func (x *GetObservabilityAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservabilityAccessRequest.ProtoReflect.Descriptor instead.
func (*GetObservabilityAccessRequest) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_access_proto_rawDescGZIP(), []int{0}
}

func (x *GetObservabilityAccessRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetObservabilityAccessRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type GetObservabilityAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ClusterAccess       `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservabilityAccessResponse) Reset() {
	*x = GetObservabilityAccessResponse{}
	mi := &file_loco_observability_v1_observability_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservabilityAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservabilityAccessResponse) ProtoMessage() {}

func (x *GetObservabilityAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservabilityAccessResponse.ProtoReflect.Descriptor instead.
func (*GetObservabilityAccessResponse) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_access_proto_rawDescGZIP(), []int{1}
}

func (x *GetObservabilityAccessResponse) GetClusters() []*ClusterAccess {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type ClusterAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ProxyUrl      string                 `protobuf:"bytes,2,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterAccess) Reset() {
	*x = ClusterAccess{}
	mi := &file_loco_observability_v1_observability_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterAccess) ProtoMessage() {}

func (x *ClusterAccess) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterAccess.ProtoReflect.Descriptor instead.
func (*ClusterAccess) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_access_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterAccess) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterAccess) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *ClusterAccess) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_loco_observability_v1_observability_access_proto protoreflect.FileDescriptor

const file_loco_observability_v1_observability_access_proto_rawDesc = "" +
	"\n" +
	"0loco/observability/v1/observability_access.proto\x12\x15loco.observability.v1\x1a\x1bbuf/validate/validate.proto\"~\n" +
	"\x1dGetObservabilityAccessRequest\x12+\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\vworkspaceId\x120\n" +
	"\fresource_ids\x18\x02 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\xb0\x01\x01R\vresourceIds\"b\n" +
	"\x1eGetObservabilityAccessResponse\x12@\n" +
	"\bclusters\x18\x01 \x03(\v2$.loco.observability.v1.ClusterAccessR\bclusters\"c\n" +
	"\rClusterAccess\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tproxy_url\x18\x02 \x01(\tR\bproxyUrl\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region2\xa4\x01\n" +
	"\x1aObservabilityAccessService\x12\x85\x01\n" +
	"\x16GetObservabilityAccess\x124.loco.observability.v1.GetObservabilityAccessRequest\x1a5.loco.observability.v1.GetObservabilityAccessResponseBGZEgithub.com/team-loco/loco/proto/loco/observability/v1;observabilityv1b\x06proto3"

var (
	file_loco_observability_v1_observability_access_proto_rawDescOnce sync.Once
	file_loco_observability_v1_observability_access_proto_rawDescData []byte
)

func file_loco_observability_v1_observability_access_proto_rawDescGZIP() []byte {
	file_loco_observability_v1_observability_access_proto_rawDescOnce.Do(func() {
		file_loco_observability_v1_observability_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loco_observability_v1_observability_access_proto_rawDesc), len(file_loco_observability_v1_observability_access_proto_rawDesc)))
	})
	return file_loco_observability_v1_observability_access_proto_rawDescData
}

var file_loco_observability_v1_observability_access_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loco_observability_v1_observability_access_proto_goTypes = []any{
	(*GetObservabilityAccessRequest)(nil),  // 0: loco.observability.v1.GetObservabilityAccessRequest
	(*GetObservabilityAccessResponse)(nil), // 1: loco.observability.v1.GetObservabilityAccessResponse
	(*ClusterAccess)(nil),                  // 2: loco.observability.v1.ClusterAccess
}
var file_loco_observability_v1_observability_access_proto_depIdxs = []int32{
	2, // 0: loco.observability.v1.GetObservabilityAccessResponse.clusters:type_name -> loco.observability.v1.ClusterAccess
	0, // 1: loco.observability.v1.ObservabilityAccessService.GetObservabilityAccess:input_type -> loco.observability.v1.GetObservabilityAccessRequest
	1, // 2: loco.observability.v1.ObservabilityAccessService.GetObservabilityAccess:output_type -> loco.observability.v1.GetObservabilityAccessResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_loco_observability_v1_observability_access_proto_init() }
func file_loco_observability_v1_observability_access_proto_init() {
	if File_loco_observability_v1_observability_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loco_observability_v1_observability_access_proto_rawDesc), len(file_loco_observability_v1_observability_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loco_observability_v1_observability_access_proto_goTypes,
		DependencyIndexes: file_loco_observability_v1_observability_access_proto_depIdxs,
		MessageInfos:      file_loco_observability_v1_observability_access_proto_msgTypes,
	}.Build()
	File_loco_observability_v1_observability_access_proto = out.File
	file_loco_observability_v1_observability_access_proto_goTypes = nil
	file_loco_observability_v1_observability_access_proto_depIdxs = nil
}
