// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loco/observability/v1/observability.proto

package observabilityv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogOrder defines the sort order for historical log queries.
type LogOrder int32

const (
	// Default value (invalid).
	LogOrder_LOG_ORDER_UNSPECIFIED LogOrder = 0
	// Return newest logs first.
	LogOrder_LOG_ORDER_NEWEST_FIRST LogOrder = 1
	// Return oldest logs first.
	LogOrder_LOG_ORDER_OLDEST_FIRST LogOrder = 2
)

// Enum value maps for LogOrder.
var (
	LogOrder_name = map[int32]string{
		0: "LOG_ORDER_UNSPECIFIED",
		1: "LOG_ORDER_NEWEST_FIRST",
		2: "LOG_ORDER_OLDEST_FIRST",
	}
	LogOrder_value = map[string]int32{
		"LOG_ORDER_UNSPECIFIED":  0,
		"LOG_ORDER_NEWEST_FIRST": 1,
		"LOG_ORDER_OLDEST_FIRST": 2,
	}
)

func (x LogOrder) Enum() *LogOrder {
	p := new(LogOrder)
	*p = x
	return p
}

func (x LogOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_loco_observability_v1_observability_proto_enumTypes[0].Descriptor()
}

func (LogOrder) Type() protoreflect.EnumType {
	return &file_loco_observability_v1_observability_proto_enumTypes[0]
}

func (x LogOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogOrder.Descriptor instead.
func (LogOrder) EnumDescriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{0}
}

// QueryLogsRequest specifies filters and pagination for querying historical logs.
type QueryLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workspace ID to query logs from (required).
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Resource IDs to filter by (e.g., deployment IDs). Empty means all resources.
	ResourceIds []string `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	// Start of time range (inclusive).
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End of time range (inclusive).
	EndTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Full-text search against log body.
	Search string `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	// Filter by severity levels (e.g., ["ERROR", "WARN"]).
	Levels []string `protobuf:"bytes,6,rep,name=levels,proto3" json:"levels,omitempty"`
	// Filter by resource attribute key-value pairs.
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Max rows to return (clamped by guardrails).
	Limit int32 `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	// Opaque cursor for pagination (from previous response). Empty for first request.
	Cursor string `protobuf:"bytes,9,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Ordering of results (newest/oldest first).
	Order         LogOrder `protobuf:"varint,10,opt,name=order,proto3,enum=loco.observability.v1.LogOrder" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsRequest) Reset() {
	*x = QueryLogsRequest{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsRequest) ProtoMessage() {}

func (x *QueryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryLogsRequest) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{0}
}

func (x *QueryLogsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *QueryLogsRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *QueryLogsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryLogsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryLogsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryLogsRequest) GetLevels() []string {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *QueryLogsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueryLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryLogsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *QueryLogsRequest) GetOrder() LogOrder {
	if x != nil {
		return x.Order
	}
	return LogOrder_LOG_ORDER_UNSPECIFIED
}

// QueryLogsResponse contains the results of a log query.
type QueryLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log entries matching the query.
	Entries []*LogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Opaque cursor for fetching the next page. Empty if no more results.
	NextCursor string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	// Approximate count of total matched rows (best-effort, may not be exact).
	TotalMatched  int64 `protobuf:"varint,3,opt,name=total_matched,json=totalMatched,proto3" json:"total_matched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsResponse) Reset() {
	*x = QueryLogsResponse{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsResponse) ProtoMessage() {}

func (x *QueryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryLogsResponse) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{1}
}

func (x *QueryLogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryLogsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *QueryLogsResponse) GetTotalMatched() int64 {
	if x != nil {
		return x.TotalMatched
	}
	return 0
}

// LogEntry represents a single log record.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the log was emitted.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Severity level (e.g., "INFO", "ERROR", "WARN", "DEBUG").
	Severity string `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	// Log message body.
	Body string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// ID of the resource (e.g., deployment) that emitted this log.
	ResourceId string `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// OpenTelemetry trace ID (if available).
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// OpenTelemetry span ID (if available).
	SpanId string `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Resource-level attributes (e.g., pod name, namespace, image).
	ResourceAttributes map[string]string `protobuf:"bytes,7,rep,name=resource_attributes,json=resourceAttributes,proto3" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Log-level attributes (e.g., user-defined fields, request ID).
	LogAttributes map[string]string `protobuf:"bytes,8,rep,name=log_attributes,json=logAttributes,proto3" json:"log_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogEntry) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LogEntry) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEntry) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogEntry) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

func (x *LogEntry) GetLogAttributes() map[string]string {
	if x != nil {
		return x.LogAttributes
	}
	return nil
}

// TailLogsRequest specifies filters for tailing live logs.
type TailLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workspace ID to tail logs from (required).
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Resource IDs to filter by. Empty means all resources.
	ResourceIds []string `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	// Full-text search against log body.
	Search string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	// Filter by severity levels (e.g., ["ERROR", "WARN"]).
	Levels []string `protobuf:"bytes,4,rep,name=levels,proto3" json:"levels,omitempty"`
	// Filter by resource attribute key-value pairs.
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogsRequest) Reset() {
	*x = TailLogsRequest{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogsRequest) ProtoMessage() {}

func (x *TailLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogsRequest.ProtoReflect.Descriptor instead.
func (*TailLogsRequest) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{3}
}

func (x *TailLogsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *TailLogsRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *TailLogsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *TailLogsRequest) GetLevels() []string {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *TailLogsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// TailLogsResponse is a server-streamed event (log entry or heartbeat).
type TailLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event is either a new log entry or a heartbeat.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*TailLogsResponse_Entry
	//	*TailLogsResponse_Heartbeat
	Event         isTailLogsResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogsResponse) Reset() {
	*x = TailLogsResponse{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogsResponse) ProtoMessage() {}

func (x *TailLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogsResponse.ProtoReflect.Descriptor instead.
func (*TailLogsResponse) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{4}
}

func (x *TailLogsResponse) GetEvent() isTailLogsResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TailLogsResponse) GetEntry() *LogEntry {
	if x != nil {
		if x, ok := x.Event.(*TailLogsResponse_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *TailLogsResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*TailLogsResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isTailLogsResponse_Event interface {
	isTailLogsResponse_Event()
}

type TailLogsResponse_Entry struct {
	// New log entry.
	Entry *LogEntry `protobuf:"bytes,1,opt,name=entry,proto3,oneof"`
}

type TailLogsResponse_Heartbeat struct {
	// Heartbeat to indicate stream is still active.
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*TailLogsResponse_Entry) isTailLogsResponse_Event() {}

func (*TailLogsResponse_Heartbeat) isTailLogsResponse_Event() {}

// Heartbeat indicates the stream is still active (no new logs yet).
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the heartbeat.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// QueryMetricsRequest specifies a metrics query with aggregation parameters.
type QueryMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workspace ID to query metrics from (required).
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Resource IDs to filter by (required, non-empty).
	ResourceIds []string `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	// Start of time range (inclusive).
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End of time range (inclusive).
	EndTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Metric name to query (e.g., "k8s.pod.cpu_limit_utilization", "k8s.pod.memory_usage").
	MetricName string `protobuf:"bytes,5,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Aggregation window in seconds (e.g., 60 for 1-minute buckets).
	IntervalSeconds int32 `protobuf:"varint,6,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	// Aggregation function ("avg", "sum", "min", "max", "p50", "p95", "p99").
	Aggregation   string `protobuf:"bytes,7,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsRequest) Reset() {
	*x = QueryMetricsRequest{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsRequest) ProtoMessage() {}

func (x *QueryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsRequest.ProtoReflect.Descriptor instead.
func (*QueryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{6}
}

func (x *QueryMetricsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *QueryMetricsRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *QueryMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryMetricsRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *QueryMetricsRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *QueryMetricsRequest) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

// QueryMetricsResponse contains the aggregated metric data.
type QueryMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metric series (one per resource).
	Series        []*MetricSeries `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsResponse) Reset() {
	*x = QueryMetricsResponse{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsResponse) ProtoMessage() {}

func (x *QueryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsResponse.ProtoReflect.Descriptor instead.
func (*QueryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{7}
}

func (x *QueryMetricsResponse) GetSeries() []*MetricSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

// MetricSeries represents time-series data for a single resource.
type MetricSeries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the resource this series is for.
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// Labels/tags associated with this series.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Data points (sorted by timestamp).
	Points        []*MetricPoint `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSeries) Reset() {
	*x = MetricSeries{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeries) ProtoMessage() {}

func (x *MetricSeries) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSeries.ProtoReflect.Descriptor instead.
func (*MetricSeries) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{8}
}

func (x *MetricSeries) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *MetricSeries) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricSeries) GetPoints() []*MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// MetricPoint is a single aggregated metric value at a point in time.
type MetricPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the data point.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Metric value (result of aggregation function).
	Value         float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_loco_observability_v1_observability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_loco_observability_v1_observability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_loco_observability_v1_observability_proto_rawDescGZIP(), []int{9}
}

func (x *MetricPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_loco_observability_v1_observability_proto protoreflect.FileDescriptor

const file_loco_observability_v1_observability_proto_rawDesc = "" +
	"\n" +
	")loco/observability/v1/observability.proto\x12\x15loco.observability.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x05\n" +
	"\x10QueryLogsRequest\x12+\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\vworkspaceId\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\x12\x16\n" +
	"\x06levels\x18\x06 \x03(\tR\x06levels\x12K\n" +
	"\x06labels\x18\a \x03(\v23.loco.observability.v1.QueryLogsRequest.LabelsEntryR\x06labels\x12 \n" +
	"\x05limit\x18\b \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x90N(\x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\t \x01(\tR\x06cursor\x125\n" +
	"\x05order\x18\n" +
	" \x01(\x0e2\x1f.loco.observability.v1.LogOrderR\x05order\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\xa3\x01\xbaH\x9f\x01\x1a\x9c\x01\n" +
	"\x18time_range.start_lte_end\x12.start_time must be before or equal to end_time\x1aP!has(this.start_time) || !has(this.end_time) || this.start_time <= this.end_time\"\x94\x01\n" +
	"\x11QueryLogsResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.loco.observability.v1.LogEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12#\n" +
	"\rtotal_matched\x18\x03 \x01(\x03R\ftotalMatched\"\x97\x04\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\x12h\n" +
	"\x13resource_attributes\x18\a \x03(\v27.loco.observability.v1.LogEntry.ResourceAttributesEntryR\x12resourceAttributes\x12Y\n" +
	"\x0elog_attributes\x18\b \x03(\v22.loco.observability.v1.LogEntry.LogAttributesEntryR\rlogAttributes\x1aE\n" +
	"\x17ResourceAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12LogAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"\x0fTailLogsRequest\x12+\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\vworkspaceId\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x16\n" +
	"\x06levels\x18\x04 \x03(\tR\x06levels\x12J\n" +
	"\x06labels\x18\x05 \x03(\v22.loco.observability.v1.TailLogsRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x10TailLogsResponse\x127\n" +
	"\x05entry\x18\x01 \x01(\v2\x1f.loco.observability.v1.LogEntryH\x00R\x05entry\x12@\n" +
	"\theartbeat\x18\x02 \x01(\v2 .loco.observability.v1.HeartbeatH\x00R\theartbeatB\a\n" +
	"\x05event\"E\n" +
	"\tHeartbeat\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa7\x05\n" +
	"\x13QueryMetricsRequest\x12+\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\vworkspaceId\x12+\n" +
	"\fresource_ids\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\vresourceIds\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12(\n" +
	"\vmetric_name\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"metricName\x122\n" +
	"\x10interval_seconds\x18\x06 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x0fintervalSeconds\x12\xbf\x01\n" +
	"\vaggregation\x18\a \x01(\tB\x9c\x01\xbaH\x98\x01\xba\x01\x94\x01\n" +
	"\x18aggregation.valid_values\x12=aggregation must be one of: avg, sum, min, max, p50, p95, p99\x1a9this in ['avg', 'sum', 'min', 'max', 'p50', 'p95', 'p99']R\vaggregation:\xa3\x01\xbaH\x9f\x01\x1a\x9c\x01\n" +
	"\x18time_range.start_lte_end\x12.start_time must be before or equal to end_time\x1aP!has(this.start_time) || !has(this.end_time) || this.start_time <= this.end_time\"S\n" +
	"\x14QueryMetricsResponse\x12;\n" +
	"\x06series\x18\x01 \x03(\v2#.loco.observability.v1.MetricSeriesR\x06series\"\xef\x01\n" +
	"\fMetricSeries\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12G\n" +
	"\x06labels\x18\x02 \x03(\v2/.loco.observability.v1.MetricSeries.LabelsEntryR\x06labels\x12:\n" +
	"\x06points\x18\x03 \x03(\v2\".loco.observability.v1.MetricPointR\x06points\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\vMetricPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value*]\n" +
	"\bLogOrder\x12\x19\n" +
	"\x15LOG_ORDER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LOG_ORDER_NEWEST_FIRST\x10\x01\x12\x1a\n" +
	"\x16LOG_ORDER_OLDEST_FIRST\x10\x022\xc3\x02\n" +
	"\x19ObservabilityProxyService\x12^\n" +
	"\tQueryLogs\x12'.loco.observability.v1.QueryLogsRequest\x1a(.loco.observability.v1.QueryLogsResponse\x12]\n" +
	"\bTailLogs\x12&.loco.observability.v1.TailLogsRequest\x1a'.loco.observability.v1.TailLogsResponse0\x01\x12g\n" +
	"\fQueryMetrics\x12*.loco.observability.v1.QueryMetricsRequest\x1a+.loco.observability.v1.QueryMetricsResponseBGZEgithub.com/team-loco/loco/proto/loco/observability/v1;observabilityv1b\x06proto3"

var (
	file_loco_observability_v1_observability_proto_rawDescOnce sync.Once
	file_loco_observability_v1_observability_proto_rawDescData []byte
)

func file_loco_observability_v1_observability_proto_rawDescGZIP() []byte {
	file_loco_observability_v1_observability_proto_rawDescOnce.Do(func() {
		file_loco_observability_v1_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loco_observability_v1_observability_proto_rawDesc), len(file_loco_observability_v1_observability_proto_rawDesc)))
	})
	return file_loco_observability_v1_observability_proto_rawDescData
}

var file_loco_observability_v1_observability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_loco_observability_v1_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_loco_observability_v1_observability_proto_goTypes = []any{
	(LogOrder)(0),                 // 0: loco.observability.v1.LogOrder
	(*QueryLogsRequest)(nil),      // 1: loco.observability.v1.QueryLogsRequest
	(*QueryLogsResponse)(nil),     // 2: loco.observability.v1.QueryLogsResponse
	(*LogEntry)(nil),              // 3: loco.observability.v1.LogEntry
	(*TailLogsRequest)(nil),       // 4: loco.observability.v1.TailLogsRequest
	(*TailLogsResponse)(nil),      // 5: loco.observability.v1.TailLogsResponse
	(*Heartbeat)(nil),             // 6: loco.observability.v1.Heartbeat
	(*QueryMetricsRequest)(nil),   // 7: loco.observability.v1.QueryMetricsRequest
	(*QueryMetricsResponse)(nil),  // 8: loco.observability.v1.QueryMetricsResponse
	(*MetricSeries)(nil),          // 9: loco.observability.v1.MetricSeries
	(*MetricPoint)(nil),           // 10: loco.observability.v1.MetricPoint
	nil,                           // 11: loco.observability.v1.QueryLogsRequest.LabelsEntry
	nil,                           // 12: loco.observability.v1.LogEntry.ResourceAttributesEntry
	nil,                           // 13: loco.observability.v1.LogEntry.LogAttributesEntry
	nil,                           // 14: loco.observability.v1.TailLogsRequest.LabelsEntry
	nil,                           // 15: loco.observability.v1.MetricSeries.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_loco_observability_v1_observability_proto_depIdxs = []int32{
	16, // 0: loco.observability.v1.QueryLogsRequest.start_time:type_name -> google.protobuf.Timestamp
	16, // 1: loco.observability.v1.QueryLogsRequest.end_time:type_name -> google.protobuf.Timestamp
	11, // 2: loco.observability.v1.QueryLogsRequest.labels:type_name -> loco.observability.v1.QueryLogsRequest.LabelsEntry
	0,  // 3: loco.observability.v1.QueryLogsRequest.order:type_name -> loco.observability.v1.LogOrder
	3,  // 4: loco.observability.v1.QueryLogsResponse.entries:type_name -> loco.observability.v1.LogEntry
	16, // 5: loco.observability.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	12, // 6: loco.observability.v1.LogEntry.resource_attributes:type_name -> loco.observability.v1.LogEntry.ResourceAttributesEntry
	13, // 7: loco.observability.v1.LogEntry.log_attributes:type_name -> loco.observability.v1.LogEntry.LogAttributesEntry
	14, // 8: loco.observability.v1.TailLogsRequest.labels:type_name -> loco.observability.v1.TailLogsRequest.LabelsEntry
	3,  // 9: loco.observability.v1.TailLogsResponse.entry:type_name -> loco.observability.v1.LogEntry
	6,  // 10: loco.observability.v1.TailLogsResponse.heartbeat:type_name -> loco.observability.v1.Heartbeat
	16, // 11: loco.observability.v1.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	16, // 12: loco.observability.v1.QueryMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	16, // 13: loco.observability.v1.QueryMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 14: loco.observability.v1.QueryMetricsResponse.series:type_name -> loco.observability.v1.MetricSeries
	15, // 15: loco.observability.v1.MetricSeries.labels:type_name -> loco.observability.v1.MetricSeries.LabelsEntry
	10, // 16: loco.observability.v1.MetricSeries.points:type_name -> loco.observability.v1.MetricPoint
	16, // 17: loco.observability.v1.MetricPoint.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 18: loco.observability.v1.ObservabilityProxyService.QueryLogs:input_type -> loco.observability.v1.QueryLogsRequest
	4,  // 19: loco.observability.v1.ObservabilityProxyService.TailLogs:input_type -> loco.observability.v1.TailLogsRequest
	7,  // 20: loco.observability.v1.ObservabilityProxyService.QueryMetrics:input_type -> loco.observability.v1.QueryMetricsRequest
	2,  // 21: loco.observability.v1.ObservabilityProxyService.QueryLogs:output_type -> loco.observability.v1.QueryLogsResponse
	5,  // 22: loco.observability.v1.ObservabilityProxyService.TailLogs:output_type -> loco.observability.v1.TailLogsResponse
	8,  // 23: loco.observability.v1.ObservabilityProxyService.QueryMetrics:output_type -> loco.observability.v1.QueryMetricsResponse
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_loco_observability_v1_observability_proto_init() }
func file_loco_observability_v1_observability_proto_init() {
	if File_loco_observability_v1_observability_proto != nil {
		return
	}
	file_loco_observability_v1_observability_proto_msgTypes[4].OneofWrappers = []any{
		(*TailLogsResponse_Entry)(nil),
		(*TailLogsResponse_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loco_observability_v1_observability_proto_rawDesc), len(file_loco_observability_v1_observability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loco_observability_v1_observability_proto_goTypes,
		DependencyIndexes: file_loco_observability_v1_observability_proto_depIdxs,
		EnumInfos:         file_loco_observability_v1_observability_proto_enumTypes,
		MessageInfos:      file_loco_observability_v1_observability_proto_msgTypes,
	}.Build()
	File_loco_observability_v1_observability_proto = out.File
	file_loco_observability_v1_observability_proto_goTypes = nil
	file_loco_observability_v1_observability_proto_depIdxs = nil
}
