{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: loco-operator
    name: loco-operator-application-viewer
rules:
    - apiGroups:
        - infra.loco.io
      resources:
        - applications
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - infra.loco.io
      resources:
        - applications/status
      verbs:
        - get
{{- end }}
