// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: workspace/v1/workspace.proto

package workspacev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nikumar1206/loco/shared/proto/workspace/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkspaceServiceName is the fully-qualified name of the WorkspaceService service.
	WorkspaceServiceName = "loco.workspace.v1.WorkspaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkspaceServiceCreateWorkspaceProcedure is the fully-qualified name of the WorkspaceService's
	// CreateWorkspace RPC.
	WorkspaceServiceCreateWorkspaceProcedure = "/loco.workspace.v1.WorkspaceService/CreateWorkspace"
	// WorkspaceServiceGetWorkspaceProcedure is the fully-qualified name of the WorkspaceService's
	// GetWorkspace RPC.
	WorkspaceServiceGetWorkspaceProcedure = "/loco.workspace.v1.WorkspaceService/GetWorkspace"
	// WorkspaceServiceGetUserWorkspacesProcedure is the fully-qualified name of the WorkspaceService's
	// GetUserWorkspaces RPC.
	WorkspaceServiceGetUserWorkspacesProcedure = "/loco.workspace.v1.WorkspaceService/GetUserWorkspaces"
	// WorkspaceServiceListWorkspacesProcedure is the fully-qualified name of the WorkspaceService's
	// ListWorkspaces RPC.
	WorkspaceServiceListWorkspacesProcedure = "/loco.workspace.v1.WorkspaceService/ListWorkspaces"
	// WorkspaceServiceUpdateWorkspaceProcedure is the fully-qualified name of the WorkspaceService's
	// UpdateWorkspace RPC.
	WorkspaceServiceUpdateWorkspaceProcedure = "/loco.workspace.v1.WorkspaceService/UpdateWorkspace"
	// WorkspaceServiceDeleteWorkspaceProcedure is the fully-qualified name of the WorkspaceService's
	// DeleteWorkspace RPC.
	WorkspaceServiceDeleteWorkspaceProcedure = "/loco.workspace.v1.WorkspaceService/DeleteWorkspace"
	// WorkspaceServiceAddMemberProcedure is the fully-qualified name of the WorkspaceService's
	// AddMember RPC.
	WorkspaceServiceAddMemberProcedure = "/loco.workspace.v1.WorkspaceService/AddMember"
	// WorkspaceServiceRemoveMemberProcedure is the fully-qualified name of the WorkspaceService's
	// RemoveMember RPC.
	WorkspaceServiceRemoveMemberProcedure = "/loco.workspace.v1.WorkspaceService/RemoveMember"
	// WorkspaceServiceListMembersProcedure is the fully-qualified name of the WorkspaceService's
	// ListMembers RPC.
	WorkspaceServiceListMembersProcedure = "/loco.workspace.v1.WorkspaceService/ListMembers"
)

// WorkspaceServiceClient is a client for the loco.workspace.v1.WorkspaceService service.
type WorkspaceServiceClient interface {
	CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error)
	GetWorkspace(context.Context, *connect.Request[v1.GetWorkspaceRequest]) (*connect.Response[v1.GetWorkspaceResponse], error)
	GetUserWorkspaces(context.Context, *connect.Request[v1.GetUserWorkspacesRequest]) (*connect.Response[v1.GetUserWorkspacesResponse], error)
	ListWorkspaces(context.Context, *connect.Request[v1.ListWorkspacesRequest]) (*connect.Response[v1.ListWorkspacesResponse], error)
	UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error)
	DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error)
	AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error)
	RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error)
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
}

// NewWorkspaceServiceClient constructs a client for the loco.workspace.v1.WorkspaceService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkspaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkspaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workspaceServiceMethods := v1.File_workspace_v1_workspace_proto.Services().ByName("WorkspaceService").Methods()
	return &workspaceServiceClient{
		createWorkspace: connect.NewClient[v1.CreateWorkspaceRequest, v1.CreateWorkspaceResponse](
			httpClient,
			baseURL+WorkspaceServiceCreateWorkspaceProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("CreateWorkspace")),
			connect.WithClientOptions(opts...),
		),
		getWorkspace: connect.NewClient[v1.GetWorkspaceRequest, v1.GetWorkspaceResponse](
			httpClient,
			baseURL+WorkspaceServiceGetWorkspaceProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GetWorkspace")),
			connect.WithClientOptions(opts...),
		),
		getUserWorkspaces: connect.NewClient[v1.GetUserWorkspacesRequest, v1.GetUserWorkspacesResponse](
			httpClient,
			baseURL+WorkspaceServiceGetUserWorkspacesProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GetUserWorkspaces")),
			connect.WithClientOptions(opts...),
		),
		listWorkspaces: connect.NewClient[v1.ListWorkspacesRequest, v1.ListWorkspacesResponse](
			httpClient,
			baseURL+WorkspaceServiceListWorkspacesProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ListWorkspaces")),
			connect.WithClientOptions(opts...),
		),
		updateWorkspace: connect.NewClient[v1.UpdateWorkspaceRequest, v1.UpdateWorkspaceResponse](
			httpClient,
			baseURL+WorkspaceServiceUpdateWorkspaceProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("UpdateWorkspace")),
			connect.WithClientOptions(opts...),
		),
		deleteWorkspace: connect.NewClient[v1.DeleteWorkspaceRequest, v1.DeleteWorkspaceResponse](
			httpClient,
			baseURL+WorkspaceServiceDeleteWorkspaceProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("DeleteWorkspace")),
			connect.WithClientOptions(opts...),
		),
		addMember: connect.NewClient[v1.AddMemberRequest, v1.AddMemberResponse](
			httpClient,
			baseURL+WorkspaceServiceAddMemberProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("AddMember")),
			connect.WithClientOptions(opts...),
		),
		removeMember: connect.NewClient[v1.RemoveMemberRequest, v1.RemoveMemberResponse](
			httpClient,
			baseURL+WorkspaceServiceRemoveMemberProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("RemoveMember")),
			connect.WithClientOptions(opts...),
		),
		listMembers: connect.NewClient[v1.ListMembersRequest, v1.ListMembersResponse](
			httpClient,
			baseURL+WorkspaceServiceListMembersProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ListMembers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workspaceServiceClient implements WorkspaceServiceClient.
type workspaceServiceClient struct {
	createWorkspace   *connect.Client[v1.CreateWorkspaceRequest, v1.CreateWorkspaceResponse]
	getWorkspace      *connect.Client[v1.GetWorkspaceRequest, v1.GetWorkspaceResponse]
	getUserWorkspaces *connect.Client[v1.GetUserWorkspacesRequest, v1.GetUserWorkspacesResponse]
	listWorkspaces    *connect.Client[v1.ListWorkspacesRequest, v1.ListWorkspacesResponse]
	updateWorkspace   *connect.Client[v1.UpdateWorkspaceRequest, v1.UpdateWorkspaceResponse]
	deleteWorkspace   *connect.Client[v1.DeleteWorkspaceRequest, v1.DeleteWorkspaceResponse]
	addMember         *connect.Client[v1.AddMemberRequest, v1.AddMemberResponse]
	removeMember      *connect.Client[v1.RemoveMemberRequest, v1.RemoveMemberResponse]
	listMembers       *connect.Client[v1.ListMembersRequest, v1.ListMembersResponse]
}

// CreateWorkspace calls loco.workspace.v1.WorkspaceService.CreateWorkspace.
func (c *workspaceServiceClient) CreateWorkspace(ctx context.Context, req *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error) {
	return c.createWorkspace.CallUnary(ctx, req)
}

// GetWorkspace calls loco.workspace.v1.WorkspaceService.GetWorkspace.
func (c *workspaceServiceClient) GetWorkspace(ctx context.Context, req *connect.Request[v1.GetWorkspaceRequest]) (*connect.Response[v1.GetWorkspaceResponse], error) {
	return c.getWorkspace.CallUnary(ctx, req)
}

// GetUserWorkspaces calls loco.workspace.v1.WorkspaceService.GetUserWorkspaces.
func (c *workspaceServiceClient) GetUserWorkspaces(ctx context.Context, req *connect.Request[v1.GetUserWorkspacesRequest]) (*connect.Response[v1.GetUserWorkspacesResponse], error) {
	return c.getUserWorkspaces.CallUnary(ctx, req)
}

// ListWorkspaces calls loco.workspace.v1.WorkspaceService.ListWorkspaces.
func (c *workspaceServiceClient) ListWorkspaces(ctx context.Context, req *connect.Request[v1.ListWorkspacesRequest]) (*connect.Response[v1.ListWorkspacesResponse], error) {
	return c.listWorkspaces.CallUnary(ctx, req)
}

// UpdateWorkspace calls loco.workspace.v1.WorkspaceService.UpdateWorkspace.
func (c *workspaceServiceClient) UpdateWorkspace(ctx context.Context, req *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error) {
	return c.updateWorkspace.CallUnary(ctx, req)
}

// DeleteWorkspace calls loco.workspace.v1.WorkspaceService.DeleteWorkspace.
func (c *workspaceServiceClient) DeleteWorkspace(ctx context.Context, req *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error) {
	return c.deleteWorkspace.CallUnary(ctx, req)
}

// AddMember calls loco.workspace.v1.WorkspaceService.AddMember.
func (c *workspaceServiceClient) AddMember(ctx context.Context, req *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error) {
	return c.addMember.CallUnary(ctx, req)
}

// RemoveMember calls loco.workspace.v1.WorkspaceService.RemoveMember.
func (c *workspaceServiceClient) RemoveMember(ctx context.Context, req *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error) {
	return c.removeMember.CallUnary(ctx, req)
}

// ListMembers calls loco.workspace.v1.WorkspaceService.ListMembers.
func (c *workspaceServiceClient) ListMembers(ctx context.Context, req *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// WorkspaceServiceHandler is an implementation of the loco.workspace.v1.WorkspaceService service.
type WorkspaceServiceHandler interface {
	CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error)
	GetWorkspace(context.Context, *connect.Request[v1.GetWorkspaceRequest]) (*connect.Response[v1.GetWorkspaceResponse], error)
	GetUserWorkspaces(context.Context, *connect.Request[v1.GetUserWorkspacesRequest]) (*connect.Response[v1.GetUserWorkspacesResponse], error)
	ListWorkspaces(context.Context, *connect.Request[v1.ListWorkspacesRequest]) (*connect.Response[v1.ListWorkspacesResponse], error)
	UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error)
	DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error)
	AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error)
	RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error)
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
}

// NewWorkspaceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkspaceServiceHandler(svc WorkspaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workspaceServiceMethods := v1.File_workspace_v1_workspace_proto.Services().ByName("WorkspaceService").Methods()
	workspaceServiceCreateWorkspaceHandler := connect.NewUnaryHandler(
		WorkspaceServiceCreateWorkspaceProcedure,
		svc.CreateWorkspace,
		connect.WithSchema(workspaceServiceMethods.ByName("CreateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGetWorkspaceHandler := connect.NewUnaryHandler(
		WorkspaceServiceGetWorkspaceProcedure,
		svc.GetWorkspace,
		connect.WithSchema(workspaceServiceMethods.ByName("GetWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGetUserWorkspacesHandler := connect.NewUnaryHandler(
		WorkspaceServiceGetUserWorkspacesProcedure,
		svc.GetUserWorkspaces,
		connect.WithSchema(workspaceServiceMethods.ByName("GetUserWorkspaces")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceListWorkspacesHandler := connect.NewUnaryHandler(
		WorkspaceServiceListWorkspacesProcedure,
		svc.ListWorkspaces,
		connect.WithSchema(workspaceServiceMethods.ByName("ListWorkspaces")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceUpdateWorkspaceHandler := connect.NewUnaryHandler(
		WorkspaceServiceUpdateWorkspaceProcedure,
		svc.UpdateWorkspace,
		connect.WithSchema(workspaceServiceMethods.ByName("UpdateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceDeleteWorkspaceHandler := connect.NewUnaryHandler(
		WorkspaceServiceDeleteWorkspaceProcedure,
		svc.DeleteWorkspace,
		connect.WithSchema(workspaceServiceMethods.ByName("DeleteWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceAddMemberHandler := connect.NewUnaryHandler(
		WorkspaceServiceAddMemberProcedure,
		svc.AddMember,
		connect.WithSchema(workspaceServiceMethods.ByName("AddMember")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceRemoveMemberHandler := connect.NewUnaryHandler(
		WorkspaceServiceRemoveMemberProcedure,
		svc.RemoveMember,
		connect.WithSchema(workspaceServiceMethods.ByName("RemoveMember")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceListMembersHandler := connect.NewUnaryHandler(
		WorkspaceServiceListMembersProcedure,
		svc.ListMembers,
		connect.WithSchema(workspaceServiceMethods.ByName("ListMembers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/loco.workspace.v1.WorkspaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkspaceServiceCreateWorkspaceProcedure:
			workspaceServiceCreateWorkspaceHandler.ServeHTTP(w, r)
		case WorkspaceServiceGetWorkspaceProcedure:
			workspaceServiceGetWorkspaceHandler.ServeHTTP(w, r)
		case WorkspaceServiceGetUserWorkspacesProcedure:
			workspaceServiceGetUserWorkspacesHandler.ServeHTTP(w, r)
		case WorkspaceServiceListWorkspacesProcedure:
			workspaceServiceListWorkspacesHandler.ServeHTTP(w, r)
		case WorkspaceServiceUpdateWorkspaceProcedure:
			workspaceServiceUpdateWorkspaceHandler.ServeHTTP(w, r)
		case WorkspaceServiceDeleteWorkspaceProcedure:
			workspaceServiceDeleteWorkspaceHandler.ServeHTTP(w, r)
		case WorkspaceServiceAddMemberProcedure:
			workspaceServiceAddMemberHandler.ServeHTTP(w, r)
		case WorkspaceServiceRemoveMemberProcedure:
			workspaceServiceRemoveMemberHandler.ServeHTTP(w, r)
		case WorkspaceServiceListMembersProcedure:
			workspaceServiceListMembersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkspaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkspaceServiceHandler struct{}

func (UnimplementedWorkspaceServiceHandler) CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.CreateWorkspace is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GetWorkspace(context.Context, *connect.Request[v1.GetWorkspaceRequest]) (*connect.Response[v1.GetWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.GetWorkspace is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GetUserWorkspaces(context.Context, *connect.Request[v1.GetUserWorkspacesRequest]) (*connect.Response[v1.GetUserWorkspacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.GetUserWorkspaces is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ListWorkspaces(context.Context, *connect.Request[v1.ListWorkspacesRequest]) (*connect.Response[v1.ListWorkspacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.ListWorkspaces is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.UpdateWorkspace is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.DeleteWorkspace is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.AddMember is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.RemoveMember is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("loco.workspace.v1.WorkspaceService.ListMembers is not implemented"))
}
