name: Workflows

on:
  push:
    branches:
      - main
      - staging
    paths:
      - ".github/workflows/**"
      - "mise.toml"
      - "mise.lock"
      - ".github/actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "mise.toml"
      - "mise.lock"
      - ".github/actions/**"
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  changes:
    name: Workflows Changes
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.changes.outputs.run }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - id: changes
        uses: ./.github/actions/merge-queue-changes

  actionlint:
    needs: changes
    if: needs.changes.outputs.run == 'true'
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-tools

      - name: actionlint and pinned actions
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mise run lint:actions
